import { Link, createFileRoute } from "@tanstack/react-router";

import { PageHeader, Panel } from "@/components/page-kit";

export const Route = createFileRoute("/terms")({
  staticData: { sitemap: false },
  head: () => ({
    meta: [
      { title: "Terms of Use | IT PATH" },
      {
        name: "description",
        content:
          "The terms that apply when you use IT PATH, the two-year IT and cybersecurity study platform by David Boley.",
      },
      { property: "og:title", content: "Terms of Use | IT PATH" },
      {
        property: "og:description",
        content: "Terms of use for IT PATH, including payment, acceptable use and termination.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: TermsPage,
});

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-2">
      <h2 className="font-display text-base font-semibold text-foreground">{title}</h2>
      <div className="space-y-3">{children}</div>
    </section>
  );
}

function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl">
      <PageHeader title="Terms of Use" description="Last updated: September 2026" />
      <Panel>
        <div className="space-y-6 text-sm leading-relaxed text-muted-foreground">
          <p>
            IT PATH is provided by <strong className="text-foreground">David Boley</strong>{" "}
            (“we”, “us”), an individual sole proprietor based in the United States,
            contactable at{" "}
            <a className="underline" href="mailto:boleydavid7@outlook.com">
              boleydavid7@outlook.com
            </a>
            . When you use IT PATH you are contracting with David Boley.
          </p>

          <Section title="1. Acceptance">
            <p>
              By creating an account or continuing to use IT PATH, you agree to these terms. If
              you do not agree, stop using the service. You must be of legal age to enter a
              contract in your country, or have permission from a parent or guardian.
            </p>
          </Section>

          <Section title="2. What IT PATH is">
            <p>
              IT PATH is a self-study platform for IT and cybersecurity: written lessons,
              practice tasks, labs, quizzes, troubleshooting incidents, spaced review, progress
              tracking and AI-assisted tutoring and marking. It is study material, it is not a
              certification body, and it does not issue CompTIA, Microsoft, Cisco or any other
              vendor certification. Passing anything inside IT PATH does not guarantee passing a
              real exam or obtaining employment.
            </p>
          </Section>

          <Section title="3. Your account">
            <p>
              Provide accurate information and keep it up to date. You are responsible for
              keeping your password confidential and for all activity under your account. Tell
              us promptly if you believe your account has been used without your permission.
            </p>
          </Section>

          <Section title="4. Acceptable use">
            <p>You must not:</p>
            <ul className="list-disc space-y-1 pl-5">
              <li>use IT PATH for anything unlawful, fraudulent or abusive, including spam;</li>
              <li>
                copy, resell, redistribute or publish the lessons, questions, labs or other
                material, or use them to train a competing product;
              </li>
              <li>
                reverse engineer the service, circumvent technical limits, share your account,
                or scrape, probe or attack the service or its infrastructure;
              </li>
              <li>
                apply anything learned here to systems you do not own or do not have written
                permission to test;
              </li>
              <li>
                submit content to the AI features that is illegal, infringing, or that you do
                not have the right to share.
              </li>
            </ul>
          </Section>

          <Section title="5. AI features">
            <p>
              The AI Tutor and AI marking are generated by a third-party language model. Output
              can be incomplete or wrong, and must not be treated as professional, legal,
              financial or security advice. Check anything important against official vendor
              documentation and exam objectives. You are responsible for what you submit as
              prompts and for how you use the responses. We may filter, restrict or refuse
              output, and may suspend accounts that misuse these features.
            </p>
          </Section>

          <Section title="6. Intellectual property">
            <p>
              We retain ownership of IT PATH, including its software, written lessons, question
              banks, labs and branding. You get a limited, non-exclusive, non-transferable right
              to use the service for your own study for as long as your access lasts. Your own
              notes, answers and portfolio entries remain yours; you grant us the limited right
              to store and process them solely in order to run the service. If you believe
              material on IT PATH infringes your rights, email us and we will review and remove
              it where appropriate.
            </p>
          </Section>

          <Section title="7. Payment and refunds">
            <p>
              Our order process is conducted by our online reseller Paddle.com. Paddle.com is the
              Merchant of Record for all our orders. Paddle provides all customer service
              inquiries and handles returns.
            </p>
            <p>
              Payment, billing, tax, cancellation and refund mechanics are governed by{" "}
              <a
                className="underline"
                href="https://www.paddle.com/legal/checkout-buyer-terms"
                target="_blank"
                rel="noreferrer"
              >
                Paddle's Buyer Terms
              </a>
              . Our own refund terms are set out in our{" "}
              <Link to="/refund-policy" className="underline">
                refund policy
              </Link>
              .
            </p>
          </Section>

          <Section title="8. Service availability">
            <p>
              We do our best to keep IT PATH running, but we do not guarantee uninterrupted or
              error-free performance. Features may change, and we may perform maintenance without
              notice. To the fullest extent permitted by law we disclaim all implied warranties,
              including merchantability and fitness for a particular purpose.
            </p>
          </Section>

          <Section title="9. Suspension and termination">
            <p>
              We may suspend or terminate access for material breach of these terms, non-payment,
              fraud or security risk, or repeated or serious misuse. You may stop using IT PATH at
              any time. Before your access ends you can export your study record and a full data
              backup from the Study record page; after termination your stored data may be
              deleted.
            </p>
          </Section>

          <Section title="10. Liability">
            <p>
              To the extent permitted by law, we are not liable for indirect, consequential or
              special damages, including lost profits, lost data or lost opportunity, and our
              total liability is limited to the amount you paid us in the twelve months before the
              claim. Nothing here excludes liability for fraud, death or personal injury where
              the law does not allow it. You agree to indemnify us against claims arising from
              your unlawful use of the service or breach of these terms.
            </p>
          </Section>

          <Section title="11. General">
            <p>
              These terms are governed by the laws of the United States and the State of the
              seller's residence, and disputes will be heard in those courts. You may not assign
              these terms without our consent; we may assign them as part of a merger or sale of
              the business. Neither party is liable for delays caused by events beyond reasonable
              control. If we update these terms we will change the date at the top of this page.
            </p>
            <p>
              Questions? Email{" "}
              <a className="underline" href="mailto:boleydavid7@outlook.com">
                boleydavid7@outlook.com
              </a>
              .
            </p>
          </Section>
        </div>
      </Panel>
    </div>
  );
}
