import { describe,expect,it } from "vitest";
import { createMachine,getNode,resolvePath } from "@/lib/terminal/machine";
import { closeApplication,createSyscalls,createVirtualKernel,enumerateDevices,launchApplication,schedule,setNetworkDeviceEnabled,setNetworkDriverHealth } from "./index";
describe("PathOS kernel foundation",()=>{
 it("keeps filesystem operations in canonical machine state",()=>{const kernel=createVirtualKernel(createMachine({shell:"cmd"}));const next=kernel.transact(state=>{expect(createSyscalls(state).fs.write("C:\\Users\\student\\Documents\\kernel.txt","PathOS")).toBeNull()});expect(getNode(next,resolvePath(next,"C:\\Users\\student\\Documents\\kernel.txt"))?.content).toBe("PathOS");expect(next.systemEvents?.some(e=>e.source==="PathFS")).toBe(true)});
 it("couples process lifecycle to memory",()=>{const kernel=createVirtualKernel(createMachine({shell:"cmd"}));let pid=0;const started=kernel.transact(state=>{pid=createSyscalls(state).process.spawn({name:"path-app.exe",memoryMb:96})});const after=started.memoryUsedMb;const stopped=createVirtualKernel(started).transact(state=>{expect(createSyscalls(state).process.kill(pid)).toBe(true)});expect(stopped.processes.some(p=>p.pid===pid)).toBe(false);expect(stopped.memoryUsedMb).toBeLessThan(after)});
 it("schedules the busiest process as running",()=>{const state=createMachine({shell:"cmd"});state.processes.push({pid:999,name:"busy",user:"student",cpu:99,memoryMb:1});expect(schedule(state)[0]?.pid).toBe(999)});
 it("launches and closes an application through its process",()=>{const app={id:"notes",name:"Notes",executable:"notes.exe",memoryMb:48,singleton:true};const kernel=createVirtualKernel(createMachine({shell:"cmd"}));let pid=0;const opened=kernel.transact(state=>{pid=launchApplication(state,app).pid});expect(opened.processes.some(p=>p.pid===pid)).toBe(true);const closed=createVirtualKernel(opened).transact(state=>{expect(closeApplication(state,app)).toBe(true)});expect(closed.processes.some(p=>p.pid===pid)).toBe(false)});
 it("derives devices from driver and interface state",()=>{const machine=createMachine({shell:"cmd"});const nic=machine.interfaces[0];expect(nic).toBeDefined();if(!nic)return;setNetworkDeviceEnabled(machine,nic.name,false);expect(enumerateDevices(machine).find(d=>d.id===`net:${nic.name}`)?.state).toBe("offline");setNetworkDriverHealth(machine,false);expect(enumerateDevices(machine).find(d=>d.id===`net:${nic.name}`)?.state).toBe("error")});
 it("tracks boot shutdown and restart lifecycle",()=>{const kernel=createVirtualKernel(createMachine({shell:"cmd"}));const before=kernel.state.bootCount??0;const off=kernel.shutdown();expect(kernel.powerState).toBe("off");expect(off.systemEvents?.some(e=>e.message.includes("Shutdown"))).toBe(true);const booted=kernel.boot();expect(kernel.powerState).toBe("running");expect(booted.bootCount).toBe(before+1)});
 it("restores a deterministic snapshot",()=>{const kernel=createVirtualKernel(createMachine({shell:"cmd"}));const snapshot=kernel.snapshot();kernel.transact(s=>{s.hostname="changed-host"});expect(kernel.restore(snapshot).hostname).toBe(snapshot.machine.hostname)});
});
