import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/state/auth-state";
export function useProfile(profileId?:string){
 const {userId,ready}=useAuth(); const id=profileId??userId; const qc=useQueryClient();
  const q=useQuery({queryKey:["profile",id],enabled:ready&&!!id,queryFn:async()=>{const {data,error}=await supabase.from("profiles").select("user_id,first_name,display_name,avatar_url").eq("user_id",id!).maybeSingle();if(error)throw error;let avatarUrl:string|null=null;const raw=data?.avatar_url??null;if(raw){if(/^https?:/.test(raw))avatarUrl=raw;else{const {data:s}=await supabase.storage.from("profile-images").createSignedUrl(raw,3600);avatarUrl=s?.signedUrl??null}}return {userId:id!,firstName:data?.first_name?.trim()??"",displayName:data?.display_name?.trim()??"",avatarUrl}}});
  const save=useMutation({mutationFn:async(firstName:string)=>{if(!userId||id!==userId)throw new Error("You can only edit your own profile.");const {error}=await supabase.from("profiles").upsert({user_id:userId,first_name:firstName.trim()||null},{onConflict:"user_id"});if(error)throw error;return firstName.trim()},onSuccess:()=>void qc.invalidateQueries({queryKey:["profile",id]})});
  const upload=useMutation({mutationFn:async(file:File)=>{if(!userId||id!==userId)throw new Error("You can only edit your own profile.");if(file.size>5*1024*1024)throw new Error("Keep profile pictures under 5 MB.");if(!["image/jpeg","image/png","image/webp"].includes(file.type))throw new Error("Use a JPG, PNG, or WebP image.");const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const key=`${userId}/avatar-${Date.now()}.${ext}`;const {error}=await supabase.storage.from("profile-images").upload(key,file,{contentType:file.type});if(error)throw error;const {error:e}=await supabase.from("profiles").upsert({user_id:userId,avatar_url:key},{onConflict:"user_id"});if(e)throw e;return key},onSuccess:()=>void qc.invalidateQueries({queryKey:["profile",id]})});
 const p=q.data??{userId:id??"",firstName:"",displayName:"",avatarUrl:null};
 return {profile:p,firstName:p.firstName,loading:!ready||(!!id&&q.isLoading),saveFirstName:save.mutateAsync,saving:save.isPending,uploadAvatar:upload.mutateAsync,uploading:upload.isPending,isOwn:!!userId&&id===userId};
}