// @ts-nocheck -- compact game code; strict index checks do not apply.
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Cpu, Database, Fan, HardDrive, MemoryStick, Network, RotateCcw, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const SIZE=8, TYPES=["CPU","RAM","NET","SEC","PWR","DATA"] as const;
type Kind=(typeof TYPES)[number]; type Special="row"|"col"|"emp"|"core"|null;
type Tile={id:number;type:Kind;special:Special}; type Cell={r:number;c:number}; type Motion={id:number;fromR:number;fromC:number;toR:number;toC:number};
type Run={cells:Cell[];type:Kind;axis:"row"|"col"}; let uid=1;
const tile=(type?:Kind,special:Special=null):Tile=>({id:uid++,type:type??TYPES[Math.floor(Math.random()*TYPES.length)],special});
const fresh=()=>Array.from({length:SIZE},()=>Array.from({length:SIZE},()=>tile()));
const key=(p:Cell)=>p.r+","+p.c;
function runs(b:Tile[][]){const out:Run[]=[];for(let r=0;r<SIZE;r++){let c=0;while(c<SIZE){let e=c+1;while(e<SIZE&&b[r][e].type===b[r][c].type)e++;if(e-c>=3)out.push({cells:Array.from({length:e-c},(_,i)=>({r,c:c+i})),type:b[r][c].type,axis:"row"});c=e;}}for(let c=0;c<SIZE;c++){let r=0;while(r<SIZE){let e=r+1;while(e<SIZE&&b[e][c].type===b[r][c].type)e++;if(e-r>=3)out.push({cells:Array.from({length:e-r},(_,i)=>({r:r+i,c})),type:b[r][c].type,axis:"col"});r=e;}}return out;}
function hitSet(b:Tile[][],rs:Run[]){const out=new Set<string>();rs.forEach(x=>x.cells.forEach(p=>out.add(key(p))));let changed=true;while(changed){changed=false;for(const k of [...out]){const [r,c]=k.split(",").map(Number),t=b[r]?.[c];if(!t?.special)continue;if(t.special==="row")for(let x=0;x<SIZE;x++){const q=r+","+x;if(!out.has(q)){out.add(q);changed=true;}}if(t.special==="col")for(let x=0;x<SIZE;x++){const q=x+","+c;if(!out.has(q)){out.add(q);changed=true;}}if(t.special==="emp")for(let rr=Math.max(0,r-1);rr<=Math.min(SIZE-1,r+1);rr++)for(let cc=Math.max(0,c-1);cc<=Math.min(SIZE-1,c+1);cc++){const q=rr+","+cc;if(!out.has(q)){out.add(q);changed=true;}}if(t.special==="core")for(let rr=0;rr<SIZE;rr++)for(let cc=0;cc<SIZE;cc++)if(b[rr][cc].type===t.type){const q=rr+","+cc;if(!out.has(q)){out.add(q);changed=true;}}}}return out;}
function stable(){let b=fresh();for(let i=0;i<40&&runs(b).length;i++)b=fresh();return b;}
const icon=(t:Tile)=>{const p={className:"size-[55%] drop-shadow-[0_2px_5px_rgba(0,0,0,.45)]",strokeWidth:1.7};if(t.special==="core")return <Cpu {...p} className="size-[64%] drop-shadow-[0_0_8px_currentColor]"/>;if(t.special==="emp")return <Zap {...p} className="size-[62%] text-warning drop-shadow-[0_0_8px_currentColor]"/>;if(t.type==="CPU")return <Cpu {...p}/>;if(t.type==="RAM")return <MemoryStick {...p}/>;if(t.type==="NET")return <Network {...p}/>;if(t.type==="SEC")return <ShieldCheck {...p}/>;if(t.type==="PWR")return <Zap {...p}/>;return <Database {...p}/>;};
const BUILD=["Case","Power supply","Motherboard","CPU","Memory","Storage","Graphics card","Cooling"] as const;
const BUILD_ICONS=[Database,Zap,Network,Cpu,MemoryStick,HardDrive,Sparkles,Fan];
const RIGS=[
 {name:"Starter PC",tag:"FOUNDATION",accent:"cyan"},
 {name:"Gaming Rig",tag:"PERFORMANCE",accent:"violet"},
 {name:"Creator Workstation",tag:"PRO",accent:"amber"},
 {name:"Lab Server",tag:"ENTERPRISE",accent:"emerald"},
] as const;
const targetFor=(level:number)=>2200+(level-1)*350;
const objectiveFor=(level:number)=>level%4===2?{kind:"collect" as const,type:TYPES[level%TYPES.length],need:18}:level%4===3?{kind:"corrupt" as const,need:6}:{kind:"score" as const,need:targetFor(level)};
const corruptFor=(level:number)=>{const out=new Set<string>();if(level%4!==3)return out;for(let i=0;i<6;i++)out.add(((i*3+level)%SIZE)+","+((i*5+level)%SIZE));return out;};
function comboHit(a:Cell,b:Cell,ta:Tile,tb:Tile){const out=new Set<string>(),add=(r:number,c:number)=>{if(r>=0&&r<SIZE&&c>=0&&c<SIZE)out.add(r+","+c)};if(ta.special==="core"&&tb.special==="core"){for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)add(r,c);return out;}if(ta.special==="core"||tb.special==="core"){const type=(ta.special==="core"?tb:ta).type;return {type} as any;}if((ta.special==="row"||ta.special==="col")&&(tb.special==="row"||tb.special==="col")){for(let x=0;x<SIZE;x++){add(a.r,x);add(x,a.c);add(b.r,x);add(x,b.c);}return out;}const radius=ta.special==="emp"&&tb.special==="emp"?2:1;for(const p of [a,b])for(let r=p.r-radius;r<=p.r+radius;r++)for(let c=p.c-radius;c<=p.c+radius;c++)add(r,c);return out;}
const saved=()=>{if(typeof window==="undefined")return {level:1,parts:0};try{return JSON.parse(localStorage.getItem("byte-break-progress")||"null")||{level:1,parts:0};}catch{return {level:1,parts:0};}};

export function ByteBreak(){
 const initial=saved(),[showGarage,setShowGarage]=useState(false),[board,setBoard]=useState<Tile[][]>(stable),[selected,setSelected]=useState<Cell|null>(null),[score,setScore]=useState(0),[moves,setMoves]=useState(30),[combo,setCombo]=useState(0),[clearing,setClearing]=useState(new Set<string>()),[motions,setMotions]=useState<Motion[]>([]),[swapMotion,setSwapMotion]=useState<{a:Cell;b:Cell}|null>(null),[level,setLevel]=useState(initial.level),[parts,setParts]=useState(initial.parts),[won,setWon]=useState(false),[powerFx,setPowerFx]=useState<{cells:Set<string>;kind:"line"|"core"}|null>(null),[installing,setInstalling]=useState(false),[celebrate,setCelebrate]=useState(false),[collected,setCollected]=useState(0),[corruption,setCorruption]=useState<Set<string>>(()=>corruptFor(initial.level));
 const objective=objectiveFor(level); const busy=useRef(false),drag=useRef<{cell:Cell;x:number;y:number;pointerId:number}|null>(null),scoreRef=useRef(0);
 useEffect(()=>{localStorage.setItem("byte-break-progress",JSON.stringify({level,parts}));},[level,parts]);
 useEffect(()=>{const done=objective.kind==="score"?score>=targetFor(level):objective.kind==="collect"?collected>=objective.need:corruption.size===0;if(done&&!won){setWon(true);setCelebrate(true);const timer=setTimeout(()=>setCelebrate(false),1200);return()=>clearTimeout(timer);}},[score,collected,corruption.size,level,objective.kind,objective.need,won]);
 const resolve=useCallback(async(start:Tile[][],preferred?:Cell)=>{let b=start,chain=0;while(true){const rs=runs(b);if(!rs.length)break;chain++;setCombo(chain);const hit=hitSet(b,rs),keepers=new Map<string,Tile>();
 const intersections=new Map<string,{row:boolean;col:boolean;type:Kind}>();
 for(const run of rs)for(const p of run.cells){const v=intersections.get(key(p))??{row:false,col:false,type:run.type};v[run.axis]=true;intersections.set(key(p),v);}
 for(const [k,v] of intersections)if(v.row&&v.col){const [r,c]=k.split(",").map(Number);keepers.set(k,tile(v.type,"emp"));hit.delete(k);}
 for(const run of rs){if(run.cells.length<4)continue;const keep=(preferred&&run.cells.some(p=>key(p)===key(preferred))?preferred:run.cells[Math.floor(run.cells.length/2)]);const special:Special=run.cells.length>=5?"core":run.axis==="row"?"row":"col";if(!keepers.has(key(keep)))keepers.set(key(keep),tile(run.type,special));hit.delete(key(keep));}setClearing(hit);if(navigator.vibrate)navigator.vibrate(8);
 const specials=[...hit].map(k=>{const [rr,cc]=k.split(",").map(Number);return b[rr]?.[cc]?.special;}).filter(Boolean);
 if(specials.length){setPowerFx({cells:new Set(hit),kind:specials.includes("core")?"core":"line"});await new Promise(r=>setTimeout(r,120));}
 await new Promise(r=>setTimeout(r,220));
 if(objective.kind==="collect"){let n=0;for(const k of hit){const [rr,cc]=k.split(",").map(Number);if(b[rr]?.[cc]?.type===objective.type)n++;}if(n)setCollected(v=>v+n);}
 if(objective.kind==="corrupt")setCorruption(prev=>{const n=new Set(prev);for(const k of hit){const [rr,cc]=k.split(",").map(Number);for(let r=rr-1;r<=rr+1;r++)for(let col=cc-1;col<=cc+1;col++)n.delete(r+","+col);}return n;});
 const gain=hit.size*100*chain;scoreRef.current+=gain;setScore(scoreRef.current);const next=Array.from({length:SIZE},()=>Array<Tile>(SIZE));const motion:Motion[]=[];for(let c=0;c<SIZE;c++){const survivors:{tile:Tile;row:number}[]=[];for(let r=SIZE-1;r>=0;r--){const k=r+","+c;if(keepers.has(k))survivors.push({tile:keepers.get(k)!,row:r});else if(!hit.has(k))survivors.push({tile:b[r][c],row:r});}let dest=SIZE-1;for(const item of survivors){next[dest][c]=item.tile;if(item.row!==dest)motion.push({id:item.tile.id,fromR:item.row,fromC:c,toR:dest,toC:c});dest--;}let spawn=1;while(dest>=0){const t=tile();next[dest][c]=t;motion.push({id:t.id,fromR:-spawn,fromC:c,toR:dest,toC:c});dest--;spawn++;}}b=next;setClearing(new Set());setPowerFx(null);setMotions(motion);setBoard(b);await new Promise(r=>setTimeout(r,400));setMotions([]);}busy.current=false;if((objective.kind==="score"&&scoreRef.current>=targetFor(level))||(objective.kind==="collect"&&collected>=objective.need)||(objective.kind==="corrupt"&&corruption.size===0)){setWon(true);setCelebrate(true);setTimeout(()=>setCelebrate(false),1200);}},[level,objective.kind,objective.need,collected,corruption.size]);
 async function swap(a:Cell,b:Cell){if(busy.current||moves<=0||won||Math.abs(a.r-b.r)+Math.abs(a.c-b.c)!==1)return;busy.current=true;const old=board;const n=board.map(x=>x.slice());const ta=n[a.r][a.c],tb=n[b.r][b.c];[n[a.r][a.c],n[b.r][b.c]]=[tb,ta];setSelected(null);setSwapMotion({a,b});setBoard(n);await new Promise(r=>setTimeout(r,180));setSwapMotion(null);
  if(ta.special&&tb.special){
   let hit=comboHit(a,b,ta,tb);if((hit as any).type){hit=new Set<string>();for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(n[r][c].type===(comboHit(a,b,ta,tb) as any).type)hit.add(r+","+c);hit.add(key(a));hit.add(key(b));}
   setPowerFx({cells:new Set(hit as Set<string>),kind:ta.special==="core"||tb.special==="core"?"core":"line"});setClearing(hit as Set<string>);await new Promise(r=>setTimeout(r,360));
   const patched=n.map(row=>row.slice());for(const k of hit as Set<string>){const [r,c]=k.split(",").map(Number);patched[r][c]=tile();}
   scoreRef.current+=(hit as Set<string>).size*190;setScore(scoreRef.current);setBoard(patched);setClearing(new Set());setPowerFx(null);setMoves(m=>m-1);busy.current=false;void resolve(patched);return;
  }
  if(ta.special==="core"||tb.special==="core"){const core=ta.special==="core"?b:a,other=ta.special==="core"?a:b,type=n[other.r][other.c].type,hit=new Set<string>();for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(n[r][c].type===type)hit.add(r+","+c);hit.add(key(core));setPowerFx({cells:new Set(hit),kind:"core"});setClearing(hit);await new Promise(r=>setTimeout(r,300));setPowerFx(null);const patched=n.map(row=>row.slice());for(const k of hit){const [r,c]=k.split(",").map(Number);patched[r][c]=tile();}scoreRef.current+=hit.size*160;setScore(scoreRef.current);setBoard(patched);setClearing(new Set());setMoves(m=>m-1);busy.current=false;if(scoreRef.current>=targetFor(level)){setWon(true);setCelebrate(true);setTimeout(()=>setCelebrate(false),1200);}return;}
  if(!runs(n).length){setSwapMotion({a,b});setBoard(old);await new Promise(r=>setTimeout(r,180));setSwapMotion(null);busy.current=false;return;}setMoves(m=>m-1);void resolve(n,b);}
 function tap(r:number,c:number){if(busy.current||moves<=0||won)return;if(!selected){setSelected({r,c});return;}if(selected.r===r&&selected.c===c){setSelected(null);return;}if(Math.abs(selected.r-r)+Math.abs(selected.c-c)===1)swap(selected,{r,c});else setSelected({r,c});}
 function reset(nextLevel=level){busy.current=false;scoreRef.current=0;setCollected(0);setCorruption(corruptFor(nextLevel));setBoard(stable());setSelected(null);setScore(0);setMoves(30);setCombo(0);setClearing(new Set());setMotions([]);setSwapMotion(null);setWon(false);setLevel(nextLevel);}
 async function continueLevel(){const nl=level+1;if(level%5===0){setInstalling(true);await new Promise(r=>setTimeout(r,850));setParts(p=>p+1);await new Promise(r=>setTimeout(r,650));setInstalling(false);}reset(nl);}
 const grid=useMemo(()=>({gridTemplateColumns:`repeat(${SIZE},minmax(0,1fr))`}),[]);
 const target=targetFor(level),objectiveDone=objective.kind==="score"?score>=target:objective.kind==="collect"?collected>=objective.need:corruption.size===0,objectiveValue=objective.kind==="score"?score:objective.kind==="collect"?collected:objective.need-corruption.size,objectiveNeed=objective.kind==="score"?target:objective.need,progress=Math.min(100,Math.round(objectiveValue/objectiveNeed*100)),rigIndex=Math.floor(parts/BUILD.length),rig=RIGS[Math.min(rigIndex,RIGS.length-1)],rigParts=parts%BUILD.length,BuildIcon=BUILD_ICONS[Math.min(rigParts,BUILD_ICONS.length-1)];
 return <div className="mx-auto max-w-2xl"><div className="glass-surface overflow-hidden rounded-3xl border border-primary/25 p-3 shadow-2xl sm:p-5">
  <div className="byte-game-header mb-4 flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-primary">BYTE//BREAK · LEVEL {level}</p><p className="mt-1 text-sm text-muted-foreground">Build the rig. Match modules and forge power cores.</p></div><Button variant="ghost" size="icon" onClick={()=>reset()} aria-label="Restart"><RotateCcw className="size-4"/></Button></div>
  <div className="byte-objective mb-3"><span>MISSION</span><strong>{objective.kind==="score"?`Reach ${target.toLocaleString()} points`:objective.kind==="collect"?`Collect ${objective.need} ${objective.type} modules`:`Clear ${objective.need} corrupted nodes`}</strong><small>{objectiveValue}/{objectiveNeed}</small></div>
  <div className="mb-3 grid grid-cols-3 gap-2"><Stat label="Score" value={score.toLocaleString()}/><Stat label="Moves" value={moves}/><Stat label="Target" value={target.toLocaleString()}/></div>
  <div className="mb-4"><div className="mb-1 flex justify-between text-[10px] uppercase tracking-wider text-muted-foreground"><span>Level progress</span><span>{progress}%</span></div><div className="h-2 overflow-hidden rounded-full bg-background/60"><div className="h-full bg-primary transition-[width] duration-300" style={{width:`${progress}%`}}/></div></div>
  <div className="byte-board-shell rounded-3xl border border-primary/20 bg-background/55 p-2 shadow-inner"><span className="byte-board-scan" aria-hidden/><div className="grid touch-none gap-1.5" style={grid}>{board.map((row,r)=>row.map((t,c)=>{const k=r+","+c,sel=selected?.r===r&&selected.c===c,gone=clearing.has(k),motion=motions.find(m=>m.id===t.id);const swapFrom=swapMotion?(swapMotion.a.r===r&&swapMotion.a.c===c?swapMotion.b:swapMotion.b.r===r&&swapMotion.b.c===c?swapMotion.a:null):null;const dx=swapFrom?(swapFrom.c-c)*100:0,dy=swapFrom?(swapFrom.r-r)*100:0;return <button key={t.id} draggable={false} style={motion?{animation:"byteDrop 430ms cubic-bezier(.16,.78,.22,1) both","--drop-rows":String(motion.toR-motion.fromR)} as React.CSSProperties:swapFrom?{animation:"byteSwap 260ms cubic-bezier(.16,.9,.24,1.12) both","--swap-x":`${dx}%`,"--swap-y":`${dy}%`}:undefined} onPointerDown={e=>{if(busy.current||moves<=0||won)return;drag.current={cell:{r,c},x:e.clientX,y:e.clientY,pointerId:e.pointerId};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d||d.pointerId!==e.pointerId)return;const dx=e.clientX-d.x,dy=e.clientY-d.y,limit=e.currentTarget.getBoundingClientRect().width*.82,h=Math.abs(dx)>Math.abs(dy);e.currentTarget.style.transform=`translate3d(${h?Math.max(-limit,Math.min(limit,dx)):0}px,${h?0:Math.max(-limit,Math.min(limit,dy))}px,0) scale(1.055)`;e.currentTarget.style.zIndex="40";}} onPointerCancel={e=>{drag.current=null;e.currentTarget.style.transform="";e.currentTarget.style.zIndex="";}} onPointerUp={e=>{const d=drag.current;drag.current=null;e.currentTarget.style.transform="";e.currentTarget.style.zIndex="";if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y,threshold=e.currentTarget.getBoundingClientRect().width*.28;if(Math.max(Math.abs(dx),Math.abs(dy))>=threshold){const target=Math.abs(dx)>Math.abs(dy)?{r:d.cell.r,c:d.cell.c+(dx>0?1:-1)}:{r:d.cell.r+(dy>0?1:-1),c:d.cell.c};if(target.r>=0&&target.r<SIZE&&target.c>=0&&target.c<SIZE){swap(d.cell,target);return;}}tap(r,c);}} aria-label={`${t.type} module`} className={cn("group relative aspect-square cursor-grab select-none overflow-hidden rounded-xl border will-change-transform bg-gradient-to-br from-card/95 to-background/75 shadow-[inset_0_1px_0_rgba(255,255,255,.18),inset_0_-5px_12px_rgba(0,0,0,.28),0_7px_16px_rgba(0,0,0,.28)] transition-[transform,opacity,box-shadow] duration-200",sel?"z-10 scale-110 border-primary shadow-[0_0_28px_color-mix(in_oklab,var(--color-primary)_50%,transparent)]":"border-border/70",t.special&&"border-primary/80 shadow-[inset_0_0_18px_color-mix(in_oklab,var(--color-primary)_28%,transparent),0_0_16px_color-mix(in_oklab,var(--color-primary)_25%,transparent)]",gone&&"z-20",corruption.has(k)&&"byte-corrupted",powerFx?.cells.has(k)&&"byte-power-activate")}>
   <span className={cn("absolute inset-[7%] rounded-[28%] opacity-80 shadow-inner",gone&&"opacity-0",t.type==="CPU"&&"bg-primary/25",t.type==="RAM"&&"bg-primary/15",t.type==="NET"&&"bg-info/25",t.type==="SEC"&&"bg-success/25",t.type==="PWR"&&"bg-warning/25",t.type==="DATA"&&"bg-destructive/20")}/>{corruption.has(k)?<span className="byte-corruption-lock" aria-hidden><i/><i/><i/></span>:null}{t.special==="row"?<span className="absolute inset-x-1 top-1/2 h-0.5 bg-primary shadow-[0_0_8px_currentColor]"/>:null}{t.special==="emp"?<span className="byte-emp-mark" aria-hidden>EMP</span>:null}{t.special==="col"?<span className="absolute inset-y-1 left-1/2 w-0.5 bg-primary shadow-[0_0_8px_currentColor]"/>:null}<span className={cn("absolute inset-0 flex items-center justify-center text-foreground",t.special==="core"&&"animate-pulse text-primary",gone&&"byte-icon-explode")}><span className="byte-tile-shine" aria-hidden/>{icon(t)}{t.special?<span className="byte-special-orbit" aria-hidden/>:null}{powerFx?.cells.has(k)?<span className={cn("pointer-events-none absolute inset-0 rounded-xl",powerFx.kind==="core"?"byte-core-wave":"byte-line-wave")} aria-hidden/>:null}{gone?<span className="byte-particle-field" aria-hidden>{Array.from({length:12},(_,i)=><i key={i} className={`byte-particle byte-particle-${i+1}`}/>)}</span>:null}</span></button>}))}</div></div>
  <button type="button" onClick={()=>setShowGarage(true)} className="byte-rig-card mt-4 w-full text-left">
    <div className="byte-rig-copy"><div className="flex items-center gap-2"><span className="byte-rig-status"/><p className="text-[9px] font-semibold uppercase tracking-[.22em] text-primary">{rig.tag} BUILD</p></div><p className="mt-1 font-display text-base font-semibold">{rig.name}</p><p className="mt-0.5 text-xs text-muted-foreground">Next install: {BUILD[rigParts]} · Level {Math.ceil((parts+1)*5)}</p></div>
    <MiniRig installed={rigParts}/>
    <div className="byte-rig-meter"><span style={{width:`${rigParts/BUILD.length*100}%`}}/><small>{rigParts}/{BUILD.length}</small></div>
  </button>
  {celebrate?<div className="byte-level-celebration" aria-hidden>{Array.from({length:18},(_,i)=><i key={i} style={{"--i":i} as React.CSSProperties}/>)}</div>:null}
  <div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span className="flex items-center gap-2"><Sparkles className="size-4 text-primary"/>4 = line · T/L = EMP · 5 = Core</span><span className="font-mono text-primary">{combo>1?`CHAIN x${combo}`:""}</span></div>
  {showGarage?<Garage rig={rig} installed={rigParts} completed={rigIndex} onClose={()=>setShowGarage(false)}/>:null}
  {installing?<div className="byte-install-overlay" aria-live="polite"><div className="byte-install-part"><Cpu className="size-14"/><span className="byte-install-ring"/><span className="byte-install-ring byte-install-ring-2"/></div><p className="mt-5 font-display text-xl font-semibold">Installing {BUILD[Math.min(parts,BUILD.length-1)]}</p><p className="mt-1 text-sm text-muted-foreground">Component locked into the build</p></div>:null}
  {won?<div className="mt-3 rounded-2xl border border-primary/30 bg-primary/10 p-4 text-center"><Sparkles className="mx-auto mb-2 size-6 text-primary"/><p className="font-display text-lg font-semibold">Level {level} complete</p><p className="text-sm text-muted-foreground">{level%5===0?`${BUILD[Math.min(parts,BUILD.length-1)]} unlocked for your build.`:"Rig progress secured. Next diagnostic grid ready."}</p><Button className="mt-3" onClick={continueLevel}>{level%5===0?"Install part & continue":"Next level"}</Button></div>:moves<=0?<div className="mt-3 rounded-2xl border border-destructive/25 bg-destructive/10 p-4 text-center"><p className="font-display text-lg font-semibold">Out of moves</p><p className="text-sm text-muted-foreground">You reached {score.toLocaleString()} / {target.toLocaleString()}</p><Button className="mt-3" onClick={()=>reset()}>Retry level</Button></div>:null}
 </div></div>;
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-border/60 bg-background/35 px-3 py-2"><p className="text-[9px] uppercase tracking-widest text-muted-foreground">{label}</p><p className="font-mono text-lg font-bold">{value}</p></div>}

function MiniRig({installed}:{installed:number}){return <div className="byte-mini-rig" aria-hidden><div className="byte-case-frame"/><div className={cn("byte-rig-board",installed<3&&"is-locked")}/><div className={cn("byte-rig-cpu",installed<4&&"is-locked")}/><div className={cn("byte-rig-ram",installed<5&&"is-locked")}/><div className={cn("byte-rig-gpu",installed<7&&"is-locked")}/><div className={cn("byte-rig-fan",installed<8&&"is-locked")}/><span className="byte-rig-glow"/></div>}
function Garage({rig,installed,completed,onClose}:{rig:any;installed:number;completed:number;onClose:()=>void}){return <div className="byte-garage-overlay" role="dialog" aria-modal="true" aria-label="Build garage"><div className="byte-garage">
 <div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.25em] text-primary">BUILD GARAGE</p><h3 className="mt-1 font-display text-2xl font-semibold">{rig.name}</h3><p className="mt-1 text-sm text-muted-foreground">Complete five-level runs to install each component.</p></div><Button variant="ghost" size="sm" onClick={onClose}>Close</Button></div>
 <div className="byte-garage-stage"><div className="byte-garage-grid"/><div className="byte-garage-hud"><span>ASSEMBLY BAY</span><span>SYS // ONLINE</span></div><MiniRig installed={installed}/><div className="byte-platform" aria-hidden/><div className="byte-stage-light byte-stage-light-a"/><div className="byte-stage-light byte-stage-light-b"/></div>
 <div className="grid grid-cols-4 gap-2">{BUILD.map((part,i)=>{const I=BUILD_ICONS[i];return <div key={part} className={cn("byte-part-slot",i<installed&&"is-installed",i===installed&&"is-next")}><I className="size-4"/><span>{part}</span>{i<installed?<small>INSTALLED</small>:i===installed?<small>NEXT</small>:<small>LOCKED</small>}</div>})}</div>
 <div className="mt-4 flex items-center justify-between border-t border-border/50 pt-4"><div><p className="text-xs text-muted-foreground">Machines completed</p><p className="font-mono text-lg font-bold">{completed}</p></div><p className="max-w-[16rem] text-right text-xs text-muted-foreground">{installed===BUILD.length?"Build complete. The next machine raises the hardware tier.":`${BUILD.length-installed} components remain on this machine.`}</p></div>
 </div></div>}
