import { useCallback, useMemo, useRef, useState } from "react";
import { RotateCcw, Sparkles, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const SIZE=8, TYPES=["CPU","RAM","NET","SEC","PWR","DATA"] as const;
type Tile={id:number;type:(typeof TYPES)[number]}; type Cell={r:number;c:number}; let uid=1;
const tile=():Tile=>({id:uid++,type:TYPES[Math.floor(Math.random()*TYPES.length)]});
const fresh=()=>Array.from({length:SIZE},()=>Array.from({length:SIZE},tile));
function matches(b:Tile[][]){const out=new Set<string>();for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++){if(c<SIZE-2&&b[r][c].type===b[r][c+1].type&&b[r][c].type===b[r][c+2].type){let x=c;while(x<SIZE&&b[r][x].type===b[r][c].type)out.add(r+","+(x++));}if(r<SIZE-2&&b[r][c].type===b[r+1][c].type&&b[r][c].type===b[r+2][c].type){let x=r;while(x<SIZE&&b[x][c].type===b[r][c].type)out.add((x++)+","+c);}}return out;}
function stable(){let b=fresh();for(let i=0;i<30&&matches(b).size;i++)b=fresh();return b;}

export function ByteBreak(){
 const [board,setBoard]=useState<Tile[][]>(stable);const [selected,setSelected]=useState<Cell|null>(null);const [score,setScore]=useState(0);const [moves,setMoves]=useState(30);const [combo,setCombo]=useState(0);const [clearing,setClearing]=useState(new Set<string>());const busy=useRef(false);
 const resolve=useCallback(async(start:Tile[][])=>{let b=start,chain=0;while(true){const hit=matches(b);if(!hit.size)break;chain++;setClearing(hit);await new Promise(r=>setTimeout(r,240));setScore(s=>s+hit.size*100*chain);setCombo(chain);const n:(Tile|null)[][]=b.map(x=>x.slice());hit.forEach(k=>{const [r,c]=k.split(",").map(Number);n[r][c]=null;});for(let c=0;c<SIZE;c++){const keep:Tile[]=[];for(let r=SIZE-1;r>=0;r--)if(n[r][c])keep.push(n[r][c] as Tile);for(let r=SIZE-1,i=0;r>=0;r--,i++)n[r][c]=keep[i]??tile();}b=n as Tile[][];setBoard(b);setClearing(new Set());await new Promise(r=>setTimeout(r,170));}busy.current=false;},[]);
 function tap(r:number,c:number){if(busy.current||moves<=0)return;if(!selected){setSelected({r,c});return;}if(Math.abs(selected.r-r)+Math.abs(selected.c-c)!==1){setSelected({r,c});return;}const b=board.map(x=>x.slice());[b[selected.r][selected.c],b[r][c]]=[b[r][c],b[selected.r][selected.c]];setSelected(null);if(!matches(b).size){setBoard(b);setTimeout(()=>setBoard(board),160);return;}busy.current=true;setMoves(m=>m-1);setBoard(b);void resolve(b);}
 function reset(){busy.current=false;setBoard(stable());setSelected(null);setScore(0);setMoves(30);setCombo(0);setClearing(new Set());}
 const grid=useMemo(()=>({gridTemplateColumns:`repeat(${SIZE},minmax(0,1fr))`}),[]);
 return <div className="mx-auto max-w-2xl"><div className="glass-surface overflow-hidden rounded-3xl border border-primary/25 p-3 shadow-2xl sm:p-5">
  <div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.25em] text-primary">BYTE//BREAK</p><p className="mt-1 text-sm text-muted-foreground">Stabilize the core. Chain matches. Overclock the grid.</p></div><Button variant="ghost" size="icon" onClick={reset} aria-label="Restart"><RotateCcw className="size-4"/></Button></div>
  <div className="mb-3 grid grid-cols-3 gap-2"><Stat label="Score" value={score.toLocaleString()}/><Stat label="Moves" value={moves}/><Stat label="Chain" value={combo>1?`x${combo}`:"—"}/></div>
  <div className="mb-4 h-1.5 overflow-hidden rounded-full bg-background/60"><div className="h-full bg-primary transition-[width] duration-300" style={{width:`${Math.min(100,score/150)}%`}}/></div>
  <div className="rounded-3xl border border-primary/20 bg-background/55 p-2 shadow-inner"><div className="grid gap-1.5" style={grid}>{board.map((row,r)=>row.map((t,c)=>{const k=r+","+c,sel=selected?.r===r&&selected.c===c,gone=clearing.has(k);return <button key={t.id} onClick={()=>tap(r,c)} className={cn("relative aspect-square overflow-hidden rounded-xl border bg-gradient-to-br from-card/90 to-background/80 shadow-[inset_0_1px_0_rgba(255,255,255,.12),0_6px_18px_rgba(0,0,0,.25)] transition-[transform,opacity,box-shadow] duration-200 active:scale-90",sel?"scale-105 border-primary shadow-[0_0_24px_color-mix(in_oklab,var(--color-primary)_45%,transparent)]":"border-border/70",gone&&"scale-125 rotate-6 opacity-0")}><span className={cn("absolute inset-1 rounded-lg opacity-70",t.type==="CPU"&&"bg-primary/20",t.type==="RAM"&&"bg-feature-violet/20",t.type==="NET"&&"bg-info/20",t.type==="SEC"&&"bg-success/20",t.type==="PWR"&&"bg-warning/20",t.type==="DATA"&&"bg-destructive/15")}/><span className="relative z-10 flex h-full items-center justify-center font-mono text-[9px] font-bold sm:text-xs">{t.type}</span></button>}))}</div></div>
  <div className="mt-4 flex items-center justify-between rounded-2xl border border-border/60 bg-background/35 px-4 py-3 text-xs text-muted-foreground"><span className="flex items-center gap-2"><Sparkles className="size-4 text-primary"/>Match 3+. Cascades multiply score.</span><span className="flex items-center gap-1 font-mono text-primary"><Zap className="size-3.5"/>{Math.min(100,Math.round(score/150))}%</span></div>
  {moves<=0?<div className="mt-3 rounded-2xl border border-primary/30 bg-primary/10 p-4 text-center"><p className="font-display text-lg font-semibold">Core cycle complete</p><p className="text-sm text-muted-foreground">Final score {score.toLocaleString()}</p><Button className="mt-3" onClick={reset}>Run it again</Button></div>:null}
 </div></div>;
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-xl border border-border/60 bg-background/35 px-3 py-2"><p className="text-[9px] uppercase tracking-widest text-muted-foreground">{label}</p><p className="font-mono text-lg font-bold">{value}</p></div>}
