import {
  Brain,
  LayoutDashboard,
  Map,
  Route as RouteIcon,
  CalendarCheck2,
  BookOpen,
  Library,
  ClipboardList,
  FlaskConical,
  HelpCircle,
  Wrench,
  Briefcase,
  RotateCcw,
  Award,
  Users,
  FolderGit2,
  Bot,
  BookMarked,
  TrendingUp,
  LineChart,
  Target,
  Timer,
  AlarmClock,
  Compass,
  Sparkles,
  Info,
  FileDown,
  Crown,
  Settings as SettingsIcon,
  SquareTerminal,
  BrainCircuit,
  type LucideIcon,
} from "lucide-react";

export interface NavItem {
  label: string;
  to: string;
  icon: LucideIcon;
  group: "Study" | "Practice" | "Career" | "You";
  /** One line explaining what this section is for, shown in the guide and as a tooltip. */
  description: string;
  /** True if this route is gated behind Pro. A small crown is shown in the sidebar. */
  pro?: boolean;
}

export const navItems: NavItem[] = [
  {
    label: "Dashboard",
    to: "/",
    icon: LayoutDashboard,
    group: "Study",
    description: "Your progress at a glance and what to do today.",
  },
  {
    label: "My Path",
    to: "/my-path",
    icon: RouteIcon,
    group: "Study",
    description: "The ordered route through your chosen certification.",
  },
  {
    label: "Study Plan",
    to: "/study-plan",
    icon: CalendarDays,
    group: "Study",
    description: "Build one timed session from your open work and due reviews.",
  },
  {
    label: "Pomodoro",
    to: "/pomodoro",
    icon: Timer,
    group: "Study",
    description: "Focus timer that logs the minutes you actually study.",
  },
  {
    label: "Learn",
    to: "/learn",
    icon: BookOpen,
    group: "Study",
    description: "Every topic lesson, searchable, with recall and teach-back.",
  },
  {
    label: "Resources",
    to: "/resources",
    icon: Library,
    group: "Study",
    description: "Official reading and video from vendors and course authors.",
  },
  {
    label: "Practice",
    to: "/practice",
    icon: ClipboardList,
    group: "Practice",
    description: "Written tasks graded against a model answer.",
  },
  {
    label: "Labs",
    to: "/labs",
    icon: FlaskConical,
    group: "Practice",
    description: "Step-by-step hands-on walkthroughs and fault drills.",
    pro: true,
  },
  {
    label: "Daily Challenge",
    to: "/daily-challenge",
    icon: CalendarCheck2,
    group: "Practice",
    description: "One short mixed set a day, the same for everyone, tracked against your past runs.",
  },
  {
    label: "Quiz Me",
    to: "/quiz-me",
    icon: HelpCircle,
    group: "Practice",
    description: "Randomised exam-style questions on any topic or certification.",
  },
  {
    label: "Troubleshoot",
    to: "/troubleshoot",
    icon: Wrench,
    group: "Practice",
    description: "Simulated incidents: diagnose, fix, verify and document.",
    pro: true,
  },
  {
    label: "Career Mode",
    to: "/career-mode",
    icon: Briefcase,
    group: "Practice",
    description: "A simulated support queue across five job roles.",
  },
  {
    label: "Exam Simulator",
    to: "/exam",
    icon: AlarmClock,
    group: "Practice",
    description: "A full-length timed mock exam with a pass or fail report.",
    pro: true,
  },
  {
    label: "Command Line",
    to: "/command-line",
    icon: SquareTerminal,
    group: "Practice",
    description: "Practice CMD, PowerShell and Linux in safe, persistent virtual computers.",
    pro: true,
  },
  {
    label: "Weak Areas",
    to: "/weak-areas",
    icon: Target,
    group: "Practice",
    description: "A quiz built only from questions you have missed.",
  },
  {
    label: "Review",
    to: "/review",
    icon: RotateCcw,
    group: "Practice",
    description: "Spaced repetition plus your full log of mistakes.",
  },
  {
    label: "Certifications",
    to: "/certifications",
    icon: Award,
    group: "Career",
    description: "Readiness per certification and the material behind it.",
  },
  {
    label: "Career Skills",
    to: "/career-skills",
    icon: Users,
    group: "Career",
    description: "Job-ready skills scored from the work you have recorded.",
  },
  {
    label: "Portfolio",
    to: "/portfolio",
    icon: FolderGit2,
    group: "Career",
    description: "Write up completed work as evidence for employers.",
  },
  {
    label: "AI Tutor",
    to: "/ai-tutor",
    icon: Bot,
    group: "You",
    description: "Ask anything and get answers that know your weak areas.",
    pro: true,
  },
  {
    label: "Second Brain",
    to: "/knowledge",
    icon: Sparkles,
    group: "You",
    description: "Save notes, links, videos and files; IT PATH reads them and connects them to your topics.",
    pro: true,
  },
  {
    label: "Bookmarks",
    to: "/bookmarks",
    icon: BookMarked,
    group: "You",
    description: "Everything you saved, plus your topic notes.",
  },
  {
    label: "Progress",
    to: "/progress",
    icon: TrendingUp,
    group: "You",
    description: "Detailed scores per topic and per skill dimension.",
  },
  {
    label: "Learner profile",
    to: "/learner",
    icon: Brain,
    group: "You",
    description: "Mastery, retention and error patterns per concept, with what to study next.",
    pro: true,
  },
  {
    label: "Insights",
    to: "/insights",
    icon: LineChart,
    group: "You",
    description: "Trends over time: study habits, accuracy and repeated mistakes.",
  },
  {
    label: "How it works",
    to: "/guide",
    icon: Compass,
    group: "You",
    description: "What each section is for and how scoring is calculated.",
  },
  {
    label: "Meet GAYL",
    to: "/meet-gayl",
    icon: BrainCircuit,
    group: "You",
    description: "An introduction to the learning intelligence behind IT PATH.",
  },
  {
    label: "Study record",
    to: "/record",
    icon: FileDown,
    group: "You",
    description: "Download a transcript of your recorded work, or back up and restore progress.",
  },
  {
    label: "About",
    to: "/about",
    icon: Info,
    group: "You",
    description: "Who built IT PATH, version number and contact details.",
  },
  {
    label: "Go Pro",
    to: "/pricing",
    icon: Crown,
    group: "You",
    description: "One-time upgrade that unlocks the AI Tutor, AI grading, labs and more.",
  },
  {
    label: "Settings",
    to: "/settings",
    icon: SettingsIcon,
    group: "You",
    description: "Your goal, experience level, study days and session length.",
  },
];

export const navGroups = ["Study", "Practice", "Career", "You"] as const;
