import {
  Brain,
  LayoutDashboard,
  Route as RouteIcon,
  CalendarDays,
  CalendarCheck2,
  BookOpen,
  Library,
  ClipboardList,
  FlaskConical,
  HelpCircle,
  Wrench,
  Briefcase,
  RotateCcw,
  Award,
  Building2,
  FolderGit2,
  Bot,
  BookMarked,
  TrendingUp,
  Timer,
  AlarmClock,
  Compass,
  Info,
  FileDown,
  Crown,
  Settings as SettingsIcon,
  SquareTerminal,
  CircuitBoard,
  Bug,
  MessagesSquare,
  Newspaper,
  Video,
  type LucideIcon,
} from "lucide-react";

export interface NavItem {
  label: string;
  to: string;
  icon: LucideIcon;
  group: "Study" | "Practice" | "Career" | "Connect" | "You";
  /** One line explaining what this section is for, shown in the guide and as a tooltip. */
  description: string;
  /** True if this route is gated behind Pro. A small crown is shown in the sidebar. */
  pro?: boolean;
}

export const navItems: NavItem[] = [
  {
    label: "Dashboard",
    to: "/",
    icon: LayoutDashboard,
    group: "Study",
    description: "Your progress at a glance and what to do today.",
  },
  {
    label: "My Path",
    to: "/my-path",
    icon: RouteIcon,
    group: "Study",
    description: "Your route through the certification, as a list or a map.",
  },
  {
    label: "Study Plan",
    to: "/study-plan",
    icon: CalendarDays,
    group: "Study",
    description: "Build one timed session from your open work and due reviews.",
  },
  {
    label: "Pomodoro",
    to: "/pomodoro",
    icon: Timer,
    group: "Study",
    description: "Focus timer that logs the minutes you actually study.",
  },
  {
    label: "Learn",
    to: "/learn",
    icon: BookOpen,
    group: "Study",
    description: "Every topic lesson, searchable, with recall and teach-back.",
  },
  {
    label: "Resources",
    to: "/resources",
    icon: Library,
    group: "Study",
    description: "Official reading and video from vendors and course authors.",
  },
  {
    label: "Practice",
    to: "/practice",
    icon: ClipboardList,
    group: "Practice",
    description: "Written tasks graded against a model answer.",
  },
  {
    label: "Labs",
    to: "/labs",
    icon: FlaskConical,
    group: "Practice",
    description: "Step-by-step hands-on walkthroughs and fault drills.",
    pro: true,
  },
  {
    label: "Daily Challenge",
    to: "/daily-challenge",
    icon: CalendarCheck2,
    group: "Practice",
    description: "One short mixed set a day, the same for everyone, tracked against your past runs.",
  },
  {
    label: "Quiz Me",
    to: "/quiz-me",
    icon: HelpCircle,
    group: "Practice",
    description: "Randomised exam-style questions on any topic or certification.",
  },
  {
    label: "Troubleshoot",
    to: "/troubleshoot",
    icon: Wrench,
    group: "Practice",
    description: "Simulated incidents: diagnose, fix, verify and document.",
    pro: true,
  },
  {
    label: "Career Mode",
    to: "/career-mode",
    icon: Briefcase,
    group: "Practice",
    description: "A simulated support queue across five job roles.",
  },
  {
    label: "Exam Simulator",
    to: "/exam",
    icon: AlarmClock,
    group: "Practice",
    description: "A full-length timed mock exam with a pass or fail report.",
    pro: true,
  },
  {
    label: "Command Line",
    to: "/command-line",
    icon: SquareTerminal,
    group: "Practice",
    description: "Practice CMD, PowerShell and Linux in safe, persistent virtual computers.",
    pro: true,
  },
  {
    label: "Virus Run",
    to: "/virus",
    icon: Bug,
    group: "Practice",
    description: "A quick arcade game: play as the virus and breach endlessly harder systems.",
  },
  {
    label: "Explore Hardware",
    to: "/explore-hardware",
    icon: CircuitBoard,
    group: "Practice",
    description: "Tap through photos of a motherboard, RAM, GPU, drives, power supply, cooler and case to learn each part.",
  },
  {
    label: "Review",
    to: "/review",
    icon: RotateCcw,
    group: "Practice",
    description: "Spaced repetition, your mistake log and a quiz on your weak areas.",
  },
  {
    label: "Certifications",
    to: "/certifications",
    icon: Award,
    group: "Career",
    description: "Readiness per certification and the material behind it.",
  },
  {
    label: "Tech Jobs",
    to: "/tech-jobs",
    icon: Building2,
    group: "Career",
    description: "Live IT job listings, filtered by location and certification.",
  },
  {
    label: "Portfolio",
    to: "/portfolio",
    icon: FolderGit2,
    group: "Career",
    description: "Write up completed work as evidence for employers.",
  },
  {
    label: "AI Tutor",
    to: "/ai-tutor",
    icon: Bot,
    group: "You",
    description: "Ask anything and get answers that know your weak areas.",
    pro: true,
  },
  {
    label: "Second Brain",
    to: "/knowledge",
    icon: Brain,
    group: "You",
    description: "Save notes, links, videos and files; IT PATH reads them and connects them to your topics.",
    pro: true,
  },
  {
    label: "Tech News",
    to: "/tech-news",
    icon: Newspaper,
    group: "Connect",
    description: "A live feed of technology headlines, kept separate from your studies.",
  },
  {
    label: "Tech Videos",
    to: "/tech-videos",
    icon: Video,
    group: "Connect",
    description: "A scrolling feed of technology videos, played in each platform's own player.",
  },
  {
    label: "Community",
    to: "/community",
    icon: MessagesSquare,
    group: "Connect",
    description: "One shared chat room with other IT PATH learners.",
  },
  {
    label: "Bookmarks",
    to: "/bookmarks",
    icon: BookMarked,
    group: "You",
    description: "Everything you saved, plus your topic notes.",
  },
  {
    label: "Progress",
    to: "/progress",
    icon: TrendingUp,
    group: "You",
    description: "Scores, trends, your learner profile and career skills.",
  },
  {
    label: "How it works",
    to: "/guide",
    icon: Compass,
    group: "You",
    description: "What each section is for and how scoring is calculated.",
  },
  {
    label: "Study record",
    to: "/record",
    icon: FileDown,
    group: "You",
    description: "Download a transcript of your recorded work, or back up and restore progress.",
  },
  {
    label: "About",
    to: "/about",
    icon: Info,
    group: "You",
    description: "Who built IT PATH, version number and contact details.",
  },
  {
    label: "Go Pro",
    to: "/pricing",
    icon: Crown,
    group: "You",
    description: "One-time upgrade that unlocks the AI Tutor, AI grading, labs and more.",
  },
  {
    label: "Settings",
    to: "/settings",
    icon: SettingsIcon,
    group: "You",
    description: "Your goal, experience level, study days and session length.",
  },
];

export const navGroups = ["Study", "Practice", "Career", "Connect", "You"] as const;
