/**
 * Owner authored questions: pulls the numbered spreadsheets out of the owner's
 * OneDrive folders and writes them into src/data/owner-questions.ts.
 *
 * The file's leading number picks the topic: "1.xlsx" feeds topic number 1 of
 * that course, in curriculum order. Folders named for auto feed AUTO PATH;
 * anything else feeds IT PATH. This is the offline snapshot used before
 * sign-in and by tests — the app itself now syncs nightly from the same
 * spreadsheets through /api/public/sheet-sync.
 *
 * Nothing here decides whether a question is good enough to be asked. Every
 * row still passes the deterministic gate in src/lib/question-quality.ts at
 * draw time, exactly like generated questions do; this script only reports
 * what would be rejected so the owner can fix the row.
 *
 * Run: bun run scripts/import-owner-questions.ts [folder]
 */
import { writeFileSync } from "node:fs";

import { questionIssues } from "../src/lib/question-quality";
import { fileNumber, ownerQuestionFromRow, topicForNumber, type OwnerDomain } from "../src/lib/owner-questions-shared";
import type { Question } from "../src/lib/app-data/types";

const GATEWAY = "https://connector-gateway.lovable.dev/microsoft_excel";
const folderArg = process.argv[2] ?? "itpath";
const FOLDER = folderArg;
const domain: OwnerDomain = /auto/i.test(folderArg) ? "auto-repair" : "it-cybersecurity";

async function graph(path: string): Promise<any> {
  const response = await fetch(`${GATEWAY}${path}`, {
    headers: {
      Authorization: `Bearer ${process.env["LOVABLE_API_KEY"]}`,
      "X-Connection-Api-Key": `${process.env["MICROSOFT_EXCEL_API_KEY"]}`,
    },
  });
  if (!response.ok) throw new Error(`${response.status}: ${await response.text()}`);
  return response.json();
}

const banks: Record<string, Question[]> = {};
const report: string[] = [];

const folder = await graph(`/me/drive/root:/${FOLDER}:/children`);
const files: Array<{ id: string; name: string }> = (folder.value ?? [])
  .filter((item: any) => item.file && item.name.endsWith(".xlsx"))
  .sort((left: any, right: any) =>
    left.name.localeCompare(right.name, undefined, { numeric: true }),
  );

for (const file of files) {
  const number = fileNumber(file.name);
  const topic = number ? topicForNumber(domain, number) : undefined;
  if (!topic) {
    report.push(`${file.name}: filename number has no matching topic, skipped`);
    continue;
  }
  const sheets = await graph(`/me/drive/items/${file.id}/workbook/worksheets`);
  const parsed: Question[] = [];
  for (const sheet of sheets.value ?? []) {
    const used = await graph(
      `/me/drive/items/${file.id}/workbook/worksheets/${encodeURIComponent(sheet.id)}` +
        `/usedRange(valuesOnly=true)?$select=values`,
    );
    const rows: unknown[][] = used.values ?? [];
    rows.slice(1).forEach((row, index) => {
      const cells = row.map((cell) => String(cell ?? "").trim());
      if (!cells.some(Boolean)) return;
      const result = ownerQuestionFromRow(topic!, cells, file.name, index + 2);
      if (result.question && !result.rejectReasons) parsed.push(result.question);
      else if (result.question) report.push(`${file.name} row ${index + 2}: rejected (${result.rejectReasons!.join("; ")})`);
      else report.push(`${file.name} row ${index + 2}: unreadable (${result.error})`);
    });
  }
  banks[topic.topicId] = [...(banks[topic.topicId] ?? []), ...parsed];
  report.push(`${file.name} -> ${topic.title}: ${parsed.length} accepted`);
}

const body = `/**
 * Questions written by the owner in OneDrive spreadsheets.
 *
 * Generated by scripts/import-owner-questions.ts. Do not edit by hand: edit the
 * spreadsheet and the nightly sync (or this script) brings the rows in. A topic
 * listed here uses these questions in place of the generated pool.
 */
import type { Question } from "@/lib/app-data/types";

export const ownerQuestions: Record<string, Question[]> = ${JSON.stringify(banks, null, 2)};
`;

writeFileSync("src/data/owner-questions.ts", body);
console.log(report.join("\n"));
console.log(
  `\nWrote src/data/owner-questions.ts: ${Object.keys(banks).length} topic(s), ` +
    `${Object.values(banks).reduce((sum, list) => sum + list.length, 0)} question(s).`,
);
