import { topics, quizzes, labs, assignments, resources, questions, tickets, incidents, lessons } from "@/data/static-content";
import { generatedQuestions } from "@/data/question-bank";
console.log("topics", topics.length, "lessons", lessons.length);
console.log("quizzes", quizzes.length, "questions", questions.length, "genQ", generatedQuestions.length);
console.log("labs", labs.length, "assignments", assignments.length, "tickets", tickets.length, "incidents", incidents.length, "resources", resources.length);
const certs = new Map<string,number>();
for (const t of topics) certs.set(t.certificationId,(certs.get(t.certificationId)??0)+1);
console.log("topics per cert", [...certs]);
const all = [...questions, ...generatedQuestions];
console.log("no answer", all.filter(q=>q.correctAnswer.length===0 && q.acceptableAnswers.length===0).length);
console.log("no explanation", all.filter(q=>!q.explanation?.trim()).length);
console.log("choice q w/ correct not in choices", all.filter(q=>q.choices.length>0 && q.correctAnswer.some(a=>!q.choices.includes(a))).length);
const labTopics = new Set(labs.map(l=>l.topicId));
console.log("labs cover topics", labTopics.size, "of", topics.length);
const ticketTracks = new Set(tickets.map((t:any)=>t.track));
console.log("ticket tracks", [...ticketTracks]);
