import { topics, quizzes, labs, assignments, resources } from "@/data/static-content";
import { generatedQuestions } from "@/data/question-bank";
import { weekQuestions } from "@/data/week-question-bank";
import { generatedAssignments } from "@/data/assignment-generator";
import { careerTickets } from "@/data/ticket-content";
import { incidents } from "@/data/incident-content";
console.log("topics", topics.length);
console.log("quizzes", quizzes.length);
console.log("labs", labs.length);
console.log("assignments", assignments.length);
console.log("genAssign", generatedAssignments.length);
console.log("genQ", generatedQuestions.length);
console.log("weekQ", weekQuestions.length);
console.log("tickets", careerTickets.length);
console.log("incidents", incidents.length);
console.log("resources", resources.length);
const certs = new Map<string,number>();
for (const t of topics) certs.set(t.certificationId,(certs.get(t.certificationId)??0)+1);
console.log([...certs]);
const labCert = new Map<string,number>();
console.log("labs per topic sample", labs.slice(0,3).map(l=>l.id));
const noAns = generatedQuestions.filter(q=>q.correctAnswer.length===0 && q.acceptableAnswers.length===0);
console.log("questions with no answer", noAns.length);
const wNo = weekQuestions.filter(q=>q.correctAnswer.length===0 && q.acceptableAnswers.length===0);
console.log("week questions no answer", wNo.length);
const aNo = generatedAssignments.filter(a=>!(a as any).modelAnswer && !(a as any).expectedAnswer);
console.log("assignments no model answer", aNo.length);
