/**
 * Writes a generated subject to disk as a versioned, self-contained package.
 *
 * Each version lands in its own folder — `src/content/packs/<id>/<version>/` —
 * and nothing outside that folder is touched. Two versions of the same subject
 * can sit side by side, an old one is never overwritten, and activation is a
 * separate, logged step that only happens once the checks pass.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

import type { DomainPackage } from "@/domain/package";

const json = (value: unknown) => JSON.stringify(value, null, 2);

export interface EmitResult {
  folder: string;
  files: string[];
  registered: boolean;
}

function camel(id: string): string {
  return id.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase());
}

/** Write the package. Returns where it went. Never activates it. */
export function emitPackage(pkg: DomainPackage, root = "src/content/packs"): EmitResult {
  const { id, version, key } = pkg.manifest;
  const folder = `${root}/${id}/${version}`;
  if (existsSync(`${folder}/package.ts`)) {
    throw new Error(`${folder} already exists. Bump the version instead of overwriting a published package.`);
  }
  mkdirSync(folder, { recursive: true });

  const name = camel(id);
  const files: Array<[string, string]> = [
    [
      "manifest.ts",
      [
        "// Generated by the domain pipeline. One version, never edited in place.",
        'import type { DomainManifest } from "@/domain/package";',
        "",
        `export const ${name}Manifest: DomainManifest = ${json(pkg.manifest)};`,
        "",
      ].join("\n"),
    ],
    [
      "domain.ts",
      [
        "// Generated by the domain pipeline.",
        'import type { DomainDefinition } from "@/domain/types";',
        "",
        `export const ${name}Domain: DomainDefinition = ${json(pkg.definition)};`,
        "",
      ].join("\n"),
    ],
    [
      "package.ts",
      [
        "// Generated by the domain pipeline: the complete subject package.",
        'import type { DomainPackage } from "@/domain/package";',
        `import { ${name}Manifest } from "./manifest";`,
        `import { ${name}Domain } from "./domain";`,
        "",
        `export const ${name}Package: DomainPackage = {`,
        `  manifest: ${name}Manifest,`,
        `  definition: ${name}Domain,`,
        ...(
          [
            "qualifications",
            "sections",
            "lessons",
            "concepts",
            "skills",
            "prerequisites",
            "questions",
            "assessments",
            "sources",
            "rules",
          ] as const
        ).map((part) => `  ${part}: ${json(pkg[part])},`),
        ...(pkg.assessmentSizes ? [`  assessmentSizes: ${json(pkg.assessmentSizes)},`] : []),
        "};",
        "",
      ].join("\n"),
    ],
    [
      "README.md",
      [
        `# ${pkg.definition.appName} ${version}`,
        "",
        pkg.definition.summary,
        "",
        `Key: \`${key}\``,
        "",
        Object.entries(pkg.manifest.scope)
          .map(([part, count]) => `- ${count} ${part}`)
          .join("\n"),
        "",
        "This package is isolated: nothing outside this folder belongs to it.",
        "Activate it with `bun run domain:activate -- " + key + "`, which runs the",
        "checks again and refuses if anything blocking is open. `bun run domain:rollback`",
        "puts the previous subject back.",
        "",
      ].join("\n"),
    ],
  ];

  for (const [file, body] of files) writeFileSync(`${folder}/${file}`, body);
  const registered = registerPackage(pkg, folder);
  return { folder, files: files.map(([file]) => file), registered };
}

/** Add the package to the registry so it can be activated later. */
export function registerPackage(pkg: DomainPackage, folder: string, registryPath = "src/domain/registry.ts"): boolean {
  const source = readFileSync(registryPath, "utf8");
  const { key, id, version } = pkg.manifest;
  if (source.includes(`"${key}"`)) return false;

  const name = camel(id);
  const alias = `${name}${version.replace(/\./g, "_")}`;
  const importPath = folder.replace(/^src\//, "@/");
  const importLine = [
    `import { ${name}Manifest as ${alias}Manifest } from "${importPath}/manifest";`,
    `import { ${name}Domain as ${alias}Domain } from "${importPath}/domain";`,
    `import { ${name}Package as ${alias}Package } from "${importPath}/package";`,
  ].join("\n");

  const entry = [
    `  "${key}": {`,
    `    manifest: ${alias}Manifest,`,
    `    definition: ${alias}Domain,`,
    `    packageSync: ${alias}Package,`,
    `    load: async () => ${alias}Package,`,
    "  },",
  ].join("\n");

  const withImport = source.replace(/^(import .+\n)(?![\s\S]*^import )/m, `$1${importLine}\n`);
  const withEntry = withImport.replace(
    /export const registry: Record<string, RegistryEntry> = \{\n/,
    (match) => `${match}${entry}\n`,
  );
  if (withEntry === source) throw new Error("Could not register the package in the registry.");
  writeFileSync(registryPath, withEntry);
  return true;
}
