/**
 * Writes an approved draft to disk as real source files.
 *
 * A generated subject lands in `src/content/packs/<id>/` as ordinary
 * TypeScript: the domain definition, the qualification tracks with their
 * objectives, the section seeds, and the outside sources. Those are the same
 * shapes the shipped subject uses, so activating the new subject is two
 * changed lines (`src/domain/active.ts` and `src/content/course-pack.ts`).
 */
import { mkdirSync, writeFileSync } from "node:fs";

import type { DomainDraft } from "./brief";

const json = (value: unknown) => JSON.stringify(value, null, 2);

export interface EmitResult {
  folder: string;
  files: string[];
}

export function emitDraft(draft: DomainDraft, root = "src/content/packs"): EmitResult {
  const folder = `${root}/${draft.definition.id}`;
  mkdirSync(folder, { recursive: true });

  const files: Array<[string, string]> = [
    [
      "domain.ts",
      [
        "// Generated by the domain pipeline. Edit freely once you accept it.",
        'import type { DomainDefinition } from "@/domain/types";',
        "",
        `export const ${camel(draft.definition.id)}Domain: DomainDefinition = ${json(draft.definition)};`,
        "",
      ].join("\n"),
    ],
    [
      "qualifications.ts",
      [
        "// Generated by the domain pipeline.",
        `export const qualifications = ${json(draft.qualifications)} as const;`,
        "",
      ].join("\n"),
    ],
    [
      "seeds.ts",
      [
        "// Generated by the domain pipeline.",
        'import type { TopicSeed } from "@/data/curriculum/builder";',
        "",
        `export const seeds: TopicSeed[] = ${json(draft.seeds)};`,
        "",
      ].join("\n"),
    ],
    [
      "sources.ts",
      [
        "// Generated by the domain pipeline. Checked nightly by the link crawler.",
        `export const sources: Record<string, Array<{ label: string; url: string; kind: "video" | "reading" }>> = ${json(
          draft.sources,
        )};`,
        "",
      ].join("\n"),
    ],
    [
      "README.md",
      [
        `# ${draft.definition.appName}`,
        "",
        draft.definition.summary,
        "",
        `Generated subject with ${draft.qualifications.length} qualifications and ${draft.seeds.length} sections.`,
        "",
        "To run the app on this subject:",
        "",
        "1. Point `src/domain/active.ts` at the definition in `domain.ts`.",
        "2. Register `seeds.ts` in `src/data/curriculum/index.ts`.",
        "3. Point `src/content/course-pack.ts` at a pack built from these files.",
        "4. Run `bun run gate`.",
        "",
      ].join("\n"),
    ],
  ];

  for (const [name, body] of files) writeFileSync(`${folder}/${name}`, body);
  return { folder, files: files.map(([name]) => name) };
}

function camel(id: string): string {
  return id.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase());
}
