export type MobileTicketFault =
  | "battery-drain" | "wifi-off" | "mail-cache" | "cloud-sync-off"
  | "legacy-profile" | "network-cache" | "bluetooth-off" | "account-sync-off"
  | "mail-sync-off" | "retired-profile" | "storage-full" | "notifications-blocked" | "sim-disabled" | "bluetooth-unpaired" | "photos-permission" | "update-prereq" | "account-signed-out" | "background-refresh-off";

export interface MobileTrainingTicket {
  id: string;
  topicId: string;
  os: "android" | "phone";
  title: string;
  requester: string;
  brief: string;
  environment: string;
  fault: MobileTicketFault;
  verification: string[];
  hints: string[];
  explanation: string;
}

export const mobileTrainingTickets: MobileTrainingTicket[] = [
  { id:"mobile-2001", topicId:"topic-mobile-troubleshooting", os:"android", title:"A phone dies before lunch", requester:"Field Engineering", brief:"A field engineer's phone drops to 20 percent by midday. Find what is causing excessive background use, make the smallest appropriate change, and verify the device is stable.", environment:"Managed IT PATH Mobile handset", fault:"battery-drain", verification:["Identify the background-use problem","Restrict the offending background activity","Confirm battery behavior is stable"], hints:["Start with Battery rather than resetting the device.","Look for background activity that can continue while the app is not open.","Restrict the unnecessary background activity, then verify."], explanation:"Excessive background activity was draining the battery. Restricting it addresses the cause without wiping the phone." },
  { id:"mobile-2002", topicId:"topic-mobile-connectivity", os:"android", title:"No Wi-Fi on a warehouse handset", requester:"Warehouse", brief:"A warehouse handset cannot reach the intranet. Other devices are online. Diagnose the affected device and restore connectivity.", environment:"IT PATH Mobile on corporate wireless", fault:"wifi-off", verification:["Confirm the Wi-Fi radio is enabled","Confirm the device has a usable connection","Confirm the support portal is reachable"], hints:["Check the device radio state before blaming the network.","Network & internet shows whether Wi-Fi is enabled.","Restore Wi-Fi and verify through the Browser or Support app."], explanation:"The Wi-Fi radio was disabled. Restoring it fixes the device without changing the healthy network." },
  { id:"mobile-2003", topicId:"topic-mobile-configuration-and-apps", os:"android", title:"Corporate mail app crashes on launch", requester:"Sales", brief:"The work mail app closes immediately on one phone. Investigate the app rather than resetting the whole device.", environment:"IT PATH Mobile with managed Mail", fault:"mail-cache", verification:["Identify Mail as the affected app","Clear its corrupt temporary data","Confirm Mail can open normally"], hints:["This is isolated to one app.","Apps & permissions shows each app's temporary data.","Clear Mail's cache rather than erasing the device."], explanation:"Corrupt temporary Mail data caused the failure. Clearing only that app's cache is the least disruptive repair." },
  { id:"mobile-2004", topicId:"topic-mobile-configuration-and-apps", os:"phone", title:"Contacts stopped syncing", requester:"Management", brief:"A manager's phone has not synced cloud data for four days. Connectivity still works.", environment:"Managed PathOS Pocket", fault:"cloud-sync-off", verification:["Confirm connectivity is healthy","Restore cloud sync","Confirm sync remains enabled"], hints:["Separate connectivity from account sync.","Accounts & sync exposes the individual sync controls.","Restore cloud sync without resetting networking."], explanation:"Cloud sync was disabled while connectivity remained healthy. Re-enabling the service restores synchronization." },
  { id:"mobile-2005", topicId:"topic-mobile-security-and-mdm", os:"phone", title:"An old profile blocks the corporate app", requester:"Operations", brief:"A leftover configuration profile from a previous deployment is blocking app installation. Remove only the obsolete profile.", environment:"Company-managed PathOS Pocket", fault:"legacy-profile", verification:["Confirm management remains enrolled","Identify the obsolete restrictions profile","Remove only the obsolete profile"], hints:["Check management status before removing profiles.","Privacy & security shows installed management state and profiles.","Remove the legacy restriction without removing active management."], explanation:"An obsolete restrictions profile was the problem. Removing only that profile preserves the active corporate configuration." },
  { id:"mobile-2006", topicId:"topic-mobile-troubleshooting", os:"phone", title:"Phone reaches the wrong intranet server", requester:"Finance", brief:"One phone keeps reaching a retired intranet destination while other devices work normally. Investigate local network state.", environment:"PathOS Pocket on corporate Wi-Fi", fault:"network-cache", verification:["Confirm Wi-Fi is otherwise healthy","Clear the stale local network state","Confirm the support portal uses the current connection"], hints:["Other devices work, so focus on this phone.","Inspect Network & internet before changing anything.","Use the targeted network repair in the ticket tools, then verify connectivity."], explanation:"The phone retained stale local network state. Clearing it restores current network resolution without wiping the device." },
  { id:"mobile-2007", topicId:"topic-mobile-connectivity", os:"android", title:"Scanner will not reconnect", requester:"Warehouse", brief:"A paired scanner stopped reconnecting after the phone restarted. Determine whether pairing or the radio is actually at fault.", environment:"IT PATH Mobile with warehouse accessory", fault:"bluetooth-off", verification:["Confirm Bluetooth radio state","Restore Bluetooth","Leave existing pairing data intact"], hints:["Do not delete the pairing first.","Check Bluetooth itself in Settings.","Enable the radio and preserve the existing configuration."], explanation:"The Bluetooth radio was off; the accessory and pairing were not the problem." },
  { id:"mobile-2008", topicId:"topic-mobile-configuration-and-apps", os:"android", title:"Work data stopped syncing", requester:"Field Services", brief:"The phone still has network access, but work data no longer updates.", environment:"Managed IT PATH Mobile with working Wi-Fi", fault:"account-sync-off", verification:["Confirm networking works","Restore account sync","Verify sync remains enabled"], hints:["Prove connectivity before changing it.","Accounts & sync separates sync from the network.","Restore the disabled sync control only."], explanation:"Connectivity was healthy, but account synchronization was disabled." },
  { id:"mobile-2009", topicId:"topic-mobile-configuration-and-apps", os:"phone", title:"Mail stopped updating", requester:"Executive Support", brief:"The phone is online and cloud sync is healthy, but managed Mail has stopped updating.", environment:"Managed PathOS Pocket", fault:"mail-sync-off", verification:["Confirm network and cloud sync are healthy","Restore Mail sync","Confirm Mail reports normal sync"], hints:["Do not reset a connected device.","Check Mail separately from cloud sync.","Turn Mail sync back on and verify in the Mail app."], explanation:"Only Mail synchronization was disabled; restoring that setting fixes the symptom." },
  { id:"mobile-2010", topicId:"topic-mobile-security-and-mdm", os:"phone", title:"Retired test profile remains installed", requester:"Mobility Team", brief:"A managed phone still carries a retired test configuration. Preserve active management while removing the obsolete item.", environment:"Company-owned PathOS Pocket", fault:"retired-profile", verification:["Confirm management is healthy","Identify the retired test profile","Remove only the retired profile"], hints:["Confirm enrollment first.","Inspect profiles rather than wiping the device.","Remove only the retired test profile."], explanation:"Management was healthy; one obsolete test profile needed removal." },
  { id:"mobile-2011", topicId:"topic-mobile-troubleshooting", os:"android", title:"Phone cannot install the required work app", requester:"Field Services", brief:"A required work app download fails even though the phone is online. Investigate device capacity and restore enough working space without resetting the handset.", environment:"Managed IT PATH Mobile with critically low free storage", fault:"storage-full", verification:["Confirm connectivity is not the cause","Identify critically low free storage","Remove temporary data and confirm capacity is no longer critical"], hints:["Prove the phone is online before changing networking.","Check Storage and app caches.","Clear temporary data rather than deleting user files or resetting the device."], explanation:"The device had critically low free storage. Clearing temporary app data restores working capacity without destroying user content." },
  { id:"mobile-2012", topicId:"topic-mobile-configuration-and-apps", os:"phone", title:"Mail arrives but the user gets no alerts", requester:"Executive Support", brief:"New mail appears when the user opens Mail, but the phone never alerts them. Networking and synchronization are working.", environment:"Managed PathOS Pocket with healthy Mail synchronization", fault:"notifications-blocked", verification:["Confirm Mail is syncing","Identify blocked notifications","Restore notification permission without resetting Mail"], hints:["The messages are already arriving, so this is not a server or sync failure.","Compare Mail status with notification permission.","Restore alerts without changing the healthy account."], explanation:"Mail synchronization was healthy, but notification permission was disabled." },
  { id:"mobile-2013", topicId:"topic-mobile-connectivity", os:"android", title:"Cellular data unavailable away from Wi-Fi", requester:"Sales", brief:"A sales phone works on office Wi-Fi but loses data as soon as the user leaves the building. Diagnose the mobile-data path without changing the healthy Wi-Fi configuration.", environment:"IT PATH Mobile with an installed SIM", fault:"sim-disabled", verification:["Confirm Wi-Fi is unrelated to the failure","Confirm SIM state and cellular data settings","Restore the cellular path and verify it is ready"], hints:["The symptom follows leaving Wi-Fi.","Inspect Cellular & SIM rather than resetting networking.","Restore the inactive mobile-data dependency and leave Wi-Fi alone."], explanation:"The cellular path was disabled while Wi-Fi remained healthy. Restoring SIM/cellular state returns off-site connectivity." },
  { id:"mobile-2014", topicId:"topic-mobile-connectivity", os:"android", title:"Bluetooth headset stopped playing audio", requester:"Service Desk", brief:"Bluetooth is turned on, but the user’s work headset no longer appears as a connected audio device. Restore the accessory without resetting unrelated network settings.", environment:"IT PATH Mobile with Bluetooth enabled and a nearby IT PATH Buds headset", fault:"bluetooth-unpaired", verification:["Confirm Bluetooth itself is enabled","Identify that the accessory is not paired","Pair IT PATH Buds and verify it is available"], hints:["Bluetooth being on does not prove an accessory is paired.","Open Bluetooth settings and inspect the device list.","Pair the nearby IT PATH Buds."], explanation:"The Bluetooth radio was healthy; the headset pairing had been removed." },
  { id:"mobile-2015", topicId:"topic-mobile-security-and-mdm", os:"phone", title:"Photos app says it cannot access the photo library", requester:"Marketing", brief:"The Photos app opens, but the user cannot see the device photo library. The app is installed and the files were not deleted.", environment:"PathOS Pocket with Photos installed but media access denied", fault:"photos-permission", verification:["Confirm the app is installed and enabled","Identify denied photo/media permission","Restore permission and verify the library appears"], hints:["Do not assume the pictures are gone.","Inspect the app’s permissions.","Allow the existing Photos app to access its media."], explanation:"The photo library remained on the device; the app permission was denied." },
  { id:"mobile-2016", topicId:"topic-mobile-troubleshooting", os:"android", title:"System update refuses to install", requester:"Security Operations", brief:"A required mobile update is available, but installation will not begin. Determine which prerequisite is failing and complete the update without wiping the device.", environment:"IT PATH Mobile online with a low battery", fault:"update-prereq", verification:["Confirm the update is available","Identify the failed installation prerequisite","Meet the prerequisite and install the update"], hints:["Check connectivity, free storage, and battery rather than repeatedly pressing Install.","The battery is below the safe installation threshold.","Connect the simulated charger, then retry the update."], explanation:"The device battery was below the update installation threshold. Charging it above the required level allowed installation." },
  { id:"mobile-2018", topicId:"topic-mobile-configuration-and-apps", os:"phone", title:"Work Mail only updates when opened", requester:"Executive Support", brief:"Mail works when opened manually, but new work messages do not arrive in the background. Networking, notifications, and the account are healthy.", environment:"Managed PathOS Pocket with Background Refresh disabled", fault:"background-refresh-off", verification:["Confirm Mail and networking are healthy","Identify disabled Background Refresh","Restore background refresh and verify Mail can update without changing the account"], hints:["The app works in the foreground, so do not reset it.","Check Privacy & background access.","Restore Background Refresh while leaving the healthy account and notification settings alone."], explanation:"Background Refresh was disabled. Restoring it allows the healthy Mail app to update when it is not in the foreground." },
  { id:"mobile-2017", topicId:"topic-mobile-security-and-mdm", os:"phone", title:"Managed cloud services stopped syncing", requester:"Human Resources", brief:"The phone still has network access, but managed cloud content no longer syncs. Determine whether this is a connectivity, account, or enrollment problem.", environment:"Managed PathOS Pocket with healthy network connectivity", fault:"account-signed-out", verification:["Confirm the network is healthy","Identify that the managed account is signed out","Sign back in and restore managed service readiness"], hints:["Prove connectivity before touching network settings.","Check the Account screen and management state.","Restore the signed-out work account."], explanation:"The device remained online and enrolled, but the managed account had been signed out." },
];


export function isMobileSupportTicket(ticket: MobileTrainingTicket): boolean {
  return Boolean(ticket.topicId.trim() && ticket.requester.trim() && ticket.brief.trim() && ticket.fault && ticket.verification.length);
}

export interface MobileTicketLaunchContext {
  kind: "ticket";
  ticketId: string;
  topicId: string;
  surface: "virtual-mobile";
  launchPath: "/virtual-mobile";
  os: "android" | "phone";
}

export function mobileTicketLaunchContext(ticket: MobileTrainingTicket): MobileTicketLaunchContext {
  return {kind:"ticket",ticketId:ticket.id,topicId:ticket.topicId,surface:"virtual-mobile",launchPath:"/virtual-mobile",os:ticket.os};
}

export function mobileTicketLaunchHref(ticket: MobileTrainingTicket): string {
  const context=mobileTicketLaunchContext(ticket);
  const params=new URLSearchParams({activity:"ticket",ticket:context.ticketId,topic:context.topicId});
  return `${context.launchPath}?${params.toString()}`;
}
