export type MobileTicketFault =
  | "battery-drain" | "wifi-off" | "mail-cache" | "cloud-sync-off"
  | "legacy-profile" | "network-cache" | "bluetooth-off" | "account-sync-off"
  | "mail-sync-off" | "retired-profile";

export interface MobileTrainingTicket {
  id: string;
  os: "android" | "phone";
  title: string;
  requester: string;
  brief: string;
  environment: string;
  fault: MobileTicketFault;
  verification: string[];
  hints: string[];
  explanation: string;
}

export const mobileTrainingTickets: MobileTrainingTicket[] = [
  { id:"mobile-2001", os:"android", title:"A phone dies before lunch", requester:"Field Engineering", brief:"A field engineer's phone drops to 20 percent by midday. Find what is causing excessive background use, make the smallest appropriate change, and verify the device is stable.", environment:"Managed IT PATH Mobile handset", fault:"battery-drain", verification:["Identify the background-use problem","Restrict the offending background activity","Confirm battery behavior is stable"], hints:["Start with Battery rather than resetting the device.","Look for background activity that can continue while the app is not open.","Restrict the unnecessary background activity, then verify."], explanation:"Excessive background activity was draining the battery. Restricting it addresses the cause without wiping the phone." },
  { id:"mobile-2002", os:"android", title:"No Wi-Fi on a warehouse handset", requester:"Warehouse", brief:"A warehouse handset cannot reach the intranet. Other devices are online. Diagnose the affected device and restore connectivity.", environment:"IT PATH Mobile on corporate wireless", fault:"wifi-off", verification:["Confirm the Wi-Fi radio is enabled","Confirm the device has a usable connection","Confirm the support portal is reachable"], hints:["Check the device radio state before blaming the network.","Network & internet shows whether Wi-Fi is enabled.","Restore Wi-Fi and verify through the Browser or Support app."], explanation:"The Wi-Fi radio was disabled. Restoring it fixes the device without changing the healthy network." },
  { id:"mobile-2003", os:"android", title:"Corporate mail app crashes on launch", requester:"Sales", brief:"The work mail app closes immediately on one phone. Investigate the app rather than resetting the whole device.", environment:"IT PATH Mobile with managed Mail", fault:"mail-cache", verification:["Identify Mail as the affected app","Clear its corrupt temporary data","Confirm Mail can open normally"], hints:["This is isolated to one app.","Apps & permissions shows each app's temporary data.","Clear Mail's cache rather than erasing the device."], explanation:"Corrupt temporary Mail data caused the failure. Clearing only that app's cache is the least disruptive repair." },
  { id:"mobile-2004", os:"phone", title:"Contacts stopped syncing", requester:"Management", brief:"A manager's phone has not synced cloud data for four days. Connectivity still works.", environment:"Managed PathOS Pocket", fault:"cloud-sync-off", verification:["Confirm connectivity is healthy","Restore cloud sync","Confirm sync remains enabled"], hints:["Separate connectivity from account sync.","Accounts & sync exposes the individual sync controls.","Restore cloud sync without resetting networking."], explanation:"Cloud sync was disabled while connectivity remained healthy. Re-enabling the service restores synchronization." },
  { id:"mobile-2005", os:"phone", title:"An old profile blocks the corporate app", requester:"Operations", brief:"A leftover configuration profile from a previous deployment is blocking app installation. Remove only the obsolete profile.", environment:"Company-managed PathOS Pocket", fault:"legacy-profile", verification:["Confirm management remains enrolled","Identify the obsolete restrictions profile","Remove only the obsolete profile"], hints:["Check management status before removing profiles.","Privacy & security shows installed management state and profiles.","Remove the legacy restriction without removing active management."], explanation:"An obsolete restrictions profile was the problem. Removing only that profile preserves the active corporate configuration." },
  { id:"mobile-2006", os:"phone", title:"Phone reaches the wrong intranet server", requester:"Finance", brief:"One phone keeps reaching a retired intranet destination while other devices work normally. Investigate local network state.", environment:"PathOS Pocket on corporate Wi-Fi", fault:"network-cache", verification:["Confirm Wi-Fi is otherwise healthy","Clear the stale local network state","Confirm the support portal uses the current connection"], hints:["Other devices work, so focus on this phone.","Inspect Network & internet before changing anything.","Use the targeted network repair in the ticket tools, then verify connectivity."], explanation:"The phone retained stale local network state. Clearing it restores current network resolution without wiping the device." },
  { id:"mobile-2007", os:"android", title:"Scanner will not reconnect", requester:"Warehouse", brief:"A paired scanner stopped reconnecting after the phone restarted. Determine whether pairing or the radio is actually at fault.", environment:"IT PATH Mobile with warehouse accessory", fault:"bluetooth-off", verification:["Confirm Bluetooth radio state","Restore Bluetooth","Leave existing pairing data intact"], hints:["Do not delete the pairing first.","Check Bluetooth itself in Settings.","Enable the radio and preserve the existing configuration."], explanation:"The Bluetooth radio was off; the accessory and pairing were not the problem." },
  { id:"mobile-2008", os:"android", title:"Work data stopped syncing", requester:"Field Services", brief:"The phone still has network access, but work data no longer updates.", environment:"Managed IT PATH Mobile with working Wi-Fi", fault:"account-sync-off", verification:["Confirm networking works","Restore account sync","Verify sync remains enabled"], hints:["Prove connectivity before changing it.","Accounts & sync separates sync from the network.","Restore the disabled sync control only."], explanation:"Connectivity was healthy, but account synchronization was disabled." },
  { id:"mobile-2009", os:"phone", title:"Mail stopped updating", requester:"Executive Support", brief:"The phone is online and cloud sync is healthy, but managed Mail has stopped updating.", environment:"Managed PathOS Pocket", fault:"mail-sync-off", verification:["Confirm network and cloud sync are healthy","Restore Mail sync","Confirm Mail reports normal sync"], hints:["Do not reset a connected device.","Check Mail separately from cloud sync.","Turn Mail sync back on and verify in the Mail app."], explanation:"Only Mail synchronization was disabled; restoring that setting fixes the symptom." },
  { id:"mobile-2010", os:"phone", title:"Retired test profile remains installed", requester:"Mobility Team", brief:"A managed phone still carries a retired test configuration. Preserve active management while removing the obsolete item.", environment:"Company-owned PathOS Pocket", fault:"retired-profile", verification:["Confirm management is healthy","Identify the retired test profile","Remove only the retired profile"], hints:["Confirm enrollment first.","Inspect profiles rather than wiping the device.","Remove only the retired test profile."], explanation:"Management was healthy; one obsolete test profile needed removal." },
];
