import type { ShellKind, TrainingFaultKind } from "@/lib/terminal/machine";

export type TrainingSurface = "virtual-pc" | "terminal";
export interface TrainingTicket {
  id: string; topicId: string; title: string; requester: string; brief: string; environment: string;
  fault: TrainingFaultKind; surfaces: TrainingSurface[]; shells: ShellKind[]; verification: string[]; tags: string[];
}

export const trainingTickets: TrainingTicket[] = [
  { id:"ticket-1842", topicId:"topic-dns-fundamentals", title:"Websites stopped loading", requester:"Accounting", brief:"The user can still reach local company resources, but websites stopped loading by name this morning. Find the cause, make the smallest appropriate repair, and verify normal access.", environment:"User workstation on the corporate LAN", fault:"dns", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Confirm the network link remains usable","Confirm hostname resolution works","Confirm the repair did not require disabling security controls"], tags:["dns","network","help-desk"] },
  { id:"ticket-1843", topicId:"topic-network-troubleshooting", title:"Workstation has no network connection", requester:"Front Desk", brief:"The workstation suddenly lost network access. Other nearby users are still online. Diagnose the affected machine and restore connectivity.", environment:"Single workstation; surrounding network is healthy", fault:"adapter", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Confirm the interface is up","Confirm the workstation has a usable local address","Confirm a network target responds"], tags:["adapter","network","help-desk"] },
  { id:"ticket-1844", topicId:"topic-network-troubleshooting", title:"Local resources work but internet access does not", requester:"Operations", brief:"The user can communicate with devices on the local subnet, but cannot reach remote networks. Determine what is missing and restore routing.", environment:"Workstation with a valid local address", fault:"gateway", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Confirm local connectivity","Confirm a default gateway is configured","Confirm a remote target is reachable"], tags:["gateway","routing","network"] },
  { id:"ticket-1845", topicId:"topic-command-line-fundamentals", title:"Background feature stopped working", requester:"Support Queue", brief:"A workstation feature that depends on a background service has stopped working. Identify the affected service, restore it, and verify its state.", environment:"Healthy workstation except for one stopped service", fault:"service", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Identify the stopped service","Restore only the affected service","Verify it remains running"], tags:["service","process","help-desk"] },
  { id:"ticket-1846", topicId:"topic-storage", title:"Computer cannot save new work reliably", requester:"Design", brief:"The user reports save failures and very little available storage. Investigate capacity and restore a safe amount of free space.", environment:"Workstation system volume is nearly full", fault:"disk", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Identify the capacity problem","Restore adequate free space","Verify the system volume is below the critical threshold"], tags:["storage","disk","capacity"] },
  { id:"ticket-1847", topicId:"topic-user-accounts", title:"User cannot sign in", requester:"HR", brief:"A local user who signed in successfully yesterday is now unable to access the workstation. Inspect the account state and restore access without replacing the account.", environment:"Local workstation account", fault:"account", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Confirm the account exists","Restore the account to an unlocked state","Verify the original account remains present"], tags:["account","lockout","identity"] },
];

export function ticketsForSurface(surface: TrainingSurface, shell?: ShellKind): TrainingTicket[] {
  return trainingTickets.filter((ticket) => ticket.surfaces.includes(surface) && (!shell || ticket.shells.includes(shell)));
}
