import type { ShellKind, TrainingFaultKind } from "@/lib/terminal/machine";
import type { VirtualOsKey } from "@/lib/training/environment";

export type TrainingSurface = "virtual-pc" | "terminal";
export interface TrainingTicket {
  id: string; topicId: string; title: string; requester: string; brief: string; environment: string;
  fault: TrainingFaultKind; surfaces: TrainingSurface[]; shells: ShellKind[]; verification: string[]; tags: string[];
  terminalScenarioId?: string;
  difficulty?: "beginner" | "intermediate" | "advanced";
  scope?: "single-machine" | "cross-machine";
  /** OS where the user reports the symptom. Defaults to the currently open machine. */
  reporterOs?: VirtualOsKey;
  /** OS where the injected root cause lives. Defaults to reporter/current OS. */
  faultHostOs?: VirtualOsKey;
  /** Shared resource that must be available before a cross-machine incident can pass verification. */
  verifyResourceId?: string;
  /** Exact service to stop for a service-fault ticket. */
  faultTarget?: string;
  /** Application the requester is using when the symptom appears. */
  symptomApp?: "browser" | "team-files" | "print-center" | "updates";
}

export const trainingTickets: TrainingTicket[] = [
  { id:"ticket-1842", topicId:"topic-dns-fundamentals", title:"Websites stopped loading", requester:"Accounting", brief:"The user can still reach local company resources, but websites stopped loading by name this morning. Find the cause, make the smallest appropriate repair, and verify normal access.", environment:"User workstation on the corporate LAN", fault:"dns", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Confirm the network link remains usable","Confirm hostname resolution works","Confirm the repair did not require disabling security controls"], tags:["dns","network","help-desk"] },
  { id:"ticket-1843", topicId:"topic-network-troubleshooting", title:"Workstation has no network connection", requester:"Front Desk", brief:"The workstation suddenly lost network access. Other nearby users are still online. Diagnose the affected machine and restore connectivity.", environment:"Single workstation; surrounding network is healthy", fault:"adapter", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Confirm the interface is up","Confirm the workstation has a usable local address","Confirm a network target responds"], tags:["adapter","network","help-desk"] },
  { id:"ticket-1844", topicId:"topic-network-troubleshooting", title:"Local resources work but internet access does not", requester:"Operations", brief:"The user can communicate with devices on the local subnet, but cannot reach remote networks. Determine what is missing and restore routing.", environment:"Workstation with a valid local address", fault:"gateway", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Confirm local connectivity","Confirm a default gateway is configured","Confirm a remote target is reachable"], tags:["gateway","routing","network"] },
  { id:"ticket-1845", topicId:"topic-command-line-fundamentals", title:"Background feature stopped working", requester:"Support Queue", brief:"A workstation feature that depends on a background service has stopped working. Identify the affected service, restore it, and verify its state.", environment:"Healthy workstation except for one stopped service", fault:"service", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Identify the stopped service","Restore only the affected service","Verify it remains running"], tags:["service","process","help-desk"] },
  { id:"ticket-1846", topicId:"topic-storage", title:"Computer cannot save new work reliably", requester:"Design", brief:"The user reports save failures and very little available storage. Investigate capacity and restore a safe amount of free space.", environment:"Workstation system volume is nearly full", fault:"disk", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Identify the capacity problem","Restore adequate free space","Verify the system volume is below the critical threshold"], tags:["storage","disk","capacity"] },
  { id:"ticket-1847", topicId:"topic-user-accounts", title:"User cannot sign in", requester:"HR", brief:"A local user who signed in successfully yesterday is now unable to access the workstation. Inspect the account state and restore access without replacing the account.", environment:"Local workstation account", fault:"account", surfaces:["virtual-pc","terminal"], shells:["cmd","powershell","bash","mac"], verification:["Confirm the account exists","Restore the account to an unlocked state","Verify the original account remains present"], tags:["account","lockout","identity"] },
  { id:"ticket-1848", topicId:"topic-device-drivers", title:"Network disappeared after an update", requester:"Sales", brief:"The workstation lost network access immediately after a driver update. Inspect the network adapter in Device Manager, determine its device status, restore the working driver, and verify connectivity.", environment:"Windows workstation after a network adapter driver update", fault:"driver", surfaces:["virtual-pc"], shells:["cmd","powershell"], verification:["Identify the adapter driver error","Restore the adapter to a working driver state","Confirm the network interface is enabled again"], tags:["windows","driver","device-manager","network"] },
  { id:"ticket-1849", topicId:"topic-troubleshooting-methodology", title:"Accounting cannot reach the intranet", requester:"Accounting", brief:"Accounting reports that the internal company site is unavailable. Do not assume the reporting workstation is the cause. Determine the scope of the outage, identify the system responsible, restore the service, and verify access from the original workstation.", environment:"IT PATH Training LAN · Windows client and Linux-hosted intranet", fault:"service", surfaces:["virtual-pc"], shells:["cmd","powershell","bash"], verification:["Confirm the Windows workstation has normal network connectivity","Determine whether the intranet host is reachable","Restore the Linux-hosted web service","Verify the intranet is reachable from the Windows workstation"], tags:["cross-machine","linux","windows","service","network","troubleshooting"], difficulty:"advanced", scope:"cross-machine", reporterOs:"windows", faultHostOs:"linux", verifyResourceId:"intranet", faultTarget:"nginx", symptomApp:"browser" },
  { id:"ticket-1850", topicId:"topic-troubleshooting-methodology", title:"Office printer shows unavailable", requester:"Operations", brief:"The user can browse the network normally, but the office printer suddenly shows unavailable. Determine whether the problem is on the workstation or the print host, restore only the failed dependency, and verify printing is available again.", environment:"IT PATH Training LAN · Windows client and PathOS-hosted printer", fault:"service", surfaces:["virtual-pc"], shells:["cmd","powershell","mac"], verification:["Confirm the reporting workstation still has network connectivity","Determine whether the print host is reachable","Restore the print service on the correct host","Verify the office printer is available from the reporting workstation"], tags:["cross-machine","printing","service","network","troubleshooting"], difficulty:"advanced", scope:"cross-machine", reporterOs:"windows", faultHostOs:"mac", verifyResourceId:"office-printer", faultTarget:"cupsd", symptomApp:"print-center" },
  { id:"ticket-1851", topicId:"topic-troubleshooting-methodology", title:"Team Files disappeared", requester:"Accounting", brief:"The user can reach other network resources, but Team Files reports that the network path is unavailable. Trace the dependency chain, restore the file-sharing service without changing unrelated network settings, and verify the share opens again.", environment:"IT PATH Training LAN · Windows client and Windows-hosted Team Files", fault:"service", surfaces:["virtual-pc"], shells:["cmd","powershell"], verification:["Confirm the workstation network remains healthy","Identify the service responsible for the share","Restore file sharing without changing unrelated settings","Verify Team Files is reachable again"], tags:["file-sharing","service","permissions","troubleshooting"], difficulty:"intermediate", scope:"single-machine", reporterOs:"windows", faultHostOs:"windows", verifyResourceId:"shared-files", faultTarget:"LanmanServer", symptomApp:"team-files" },
  { id:"ticket-1852", topicId:"topic-storage", title:"Windows Update will not install", requester:"Support Queue", brief:"Windows Update opens, but installation cannot proceed. Diagnose the workstation instead of repeatedly retrying the update. Restore the dependency that is preventing update work and verify the update application is ready.", environment:"Windows workstation", fault:"disk", surfaces:["virtual-pc"], shells:["cmd","powershell"], verification:["Inspect update status before deleting anything","Identify the storage pressure","Restore sufficient free space safely","Verify the update application can proceed"], tags:["windows","updates","storage","troubleshooting"], difficulty:"intermediate", reporterOs:"windows", faultHostOs:"windows", symptomApp:"updates" },
];

export function ticketDifficulty(ticket: TrainingTicket): "beginner" | "intermediate" | "advanced" {
  if (ticket.difficulty) return ticket.difficulty;
  if (ticket.fault === "dns" || ticket.fault === "adapter" || ticket.fault === "account") return "beginner";
  if (ticket.fault === "gateway" || ticket.fault === "service" || ticket.fault === "disk" || ticket.fault === "driver") return "intermediate";
  return "beginner";
}

export function ticketScope(ticket: TrainingTicket): "single-machine" | "cross-machine" {
  return ticket.scope ?? "single-machine";
}

export function ticketsForSurface(surface: TrainingSurface, shell?: ShellKind): TrainingTicket[] {
  return trainingTickets.filter((ticket) => ticket.surfaces.includes(surface) && (!shell || ticket.shells.includes(shell)));
}
