/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiTutorRouteImport } from './routes/ai-tutor'
import { Route as AiUsageRouteImport } from './routes/ai-usage'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ByteBreakRouteImport } from './routes/byte-break'
import { Route as CareerModeRouteImport } from './routes/career-mode'
import { Route as CareerSkillsRouteImport } from './routes/career-skills'
import { Route as CommandLineRouteImport } from './routes/command-line'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DailyChallengeRouteImport } from './routes/daily-challenge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EngineSimulatorRouteImport } from './routes/engine-simulator'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as ExploreEngineRouteImport } from './routes/explore-engine'
import { Route as ExploreHardwareRouteImport } from './routes/explore-hardware'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LearnerRouteImport } from './routes/learner'
import { Route as MeditationRouteImport } from './routes/meditation'
import { Route as MeetGaylRouteImport } from './routes/meet-gayl'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MyPathRouteImport } from './routes/my-path'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ObdScannerRouteImport } from './routes/obd-scanner'
import { Route as PomodoroRouteImport } from './routes/pomodoro'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuizMeRouteImport } from './routes/quiz-me'
import { Route as RecordRouteImport } from './routes/record'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudyPlanRouteImport } from './routes/study-plan'
import { Route as TechJobsRouteImport } from './routes/tech-jobs'
import { Route as TechNewsRouteImport } from './routes/tech-news'
import { Route as TechVideosRouteImport } from './routes/tech-videos'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TroubleshootRouteImport } from './routes/troubleshoot'
import { Route as VirtualMobileRouteImport } from './routes/virtual-mobile'
import { Route as VirtualPcRouteImport } from './routes/virtual-pc'
import { Route as VirusRouteImport } from './routes/virus'
import { Route as WeakAreasRouteImport } from './routes/weak-areas'
import { Route as CertificationsIndexRouteImport } from './routes/certifications.index'
import { Route as CertificationsCertIdRouteImport } from './routes/certifications.$certId'
import { Route as FlashcardsIndexRouteImport } from './routes/flashcards.index'
import { Route as FlashcardsTopicIdRouteImport } from './routes/flashcards.$topicId'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as LearnVideosRouteImport } from './routes/learn.videos'
import { Route as PracticeTestsIndexRouteImport } from './routes/practice-tests.index'
import { Route as PracticeTestsCertIdRouteImport } from './routes/practice-tests.$certId'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as SectionQuizTopicIdRouteImport } from './routes/section-quiz.$topicId'
import { Route as StageExamStageIdRouteImport } from './routes/stage-exam.$stageId'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as TracksIndexRouteImport } from './routes/tracks.index'
import { Route as TracksSlugRouteImport } from './routes/tracks.$slug'
import { Route as ApiAiTutorStreamRouteImport } from './routes/api/ai/tutor-stream'
import { Route as ApiAuthMicrosoftRouteImport } from './routes/api/auth/microsoft'
import { Route as ApiPublicContentAuditRouteImport } from './routes/api/public/content-audit'
import { Route as ApiPublicLinkCheckRouteImport } from './routes/api/public/link-check'
import { Route as ApiPublicSheetSyncRouteImport } from './routes/api/public/sheet-sync'
import { Route as ApiAuthMicrosoftCallbackRouteImport } from './routes/api/auth/microsoft/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTutorRoute = AiTutorRouteImport.update({
  id: '/ai-tutor',
  path: '/ai-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AiUsageRoute = AiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ByteBreakRoute = ByteBreakRouteImport.update({
  id: '/byte-break',
  path: '/byte-break',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerModeRoute = CareerModeRouteImport.update({
  id: '/career-mode',
  path: '/career-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerSkillsRoute = CareerSkillsRouteImport.update({
  id: '/career-skills',
  path: '/career-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandLineRoute = CommandLineRouteImport.update({
  id: '/command-line',
  path: '/command-line',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyChallengeRoute = DailyChallengeRouteImport.update({
  id: '/daily-challenge',
  path: '/daily-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineSimulatorRoute = EngineSimulatorRouteImport.update({
  id: '/engine-simulator',
  path: '/engine-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreEngineRoute = ExploreEngineRouteImport.update({
  id: '/explore-engine',
  path: '/explore-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreHardwareRoute = ExploreHardwareRouteImport.update({
  id: '/explore-hardware',
  path: '/explore-hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerRoute = LearnerRouteImport.update({
  id: '/learner',
  path: '/learner',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationRoute = MeditationRouteImport.update({
  id: '/meditation',
  path: '/meditation',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetGaylRoute = MeetGaylRouteImport.update({
  id: '/meet-gayl',
  path: '/meet-gayl',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPathRoute = MyPathRouteImport.update({
  id: '/my-path',
  path: '/my-path',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ObdScannerRoute = ObdScannerRouteImport.update({
  id: '/obd-scanner',
  path: '/obd-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroRoute = PomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizMeRoute = QuizMeRouteImport.update({
  id: '/quiz-me',
  path: '/quiz-me',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPlanRoute = StudyPlanRouteImport.update({
  id: '/study-plan',
  path: '/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const TechJobsRoute = TechJobsRouteImport.update({
  id: '/tech-jobs',
  path: '/tech-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const TechNewsRoute = TechNewsRouteImport.update({
  id: '/tech-news',
  path: '/tech-news',
  getParentRoute: () => rootRouteImport,
} as any)
const TechVideosRoute = TechVideosRouteImport.update({
  id: '/tech-videos',
  path: '/tech-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TroubleshootRoute = TroubleshootRouteImport.update({
  id: '/troubleshoot',
  path: '/troubleshoot',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualMobileRoute = VirtualMobileRouteImport.update({
  id: '/virtual-mobile',
  path: '/virtual-mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualPcRoute = VirtualPcRouteImport.update({
  id: '/virtual-pc',
  path: '/virtual-pc',
  getParentRoute: () => rootRouteImport,
} as any)
const VirusRoute = VirusRouteImport.update({
  id: '/virus',
  path: '/virus',
  getParentRoute: () => rootRouteImport,
} as any)
const WeakAreasRoute = WeakAreasRouteImport.update({
  id: '/weak-areas',
  path: '/weak-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsIndexRoute = CertificationsIndexRouteImport.update({
  id: '/certifications/',
  path: '/certifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsCertIdRoute = CertificationsCertIdRouteImport.update({
  id: '/certifications/$certId',
  path: '/certifications/$certId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsIndexRoute = FlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsTopicIdRoute = FlashcardsTopicIdRouteImport.update({
  id: '/flashcards/$topicId',
  path: '/flashcards/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnVideosRoute = LearnVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => LearnRoute,
} as any)
const PracticeTestsIndexRoute = PracticeTestsIndexRouteImport.update({
  id: '/practice-tests/',
  path: '/practice-tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTestsCertIdRoute = PracticeTestsCertIdRouteImport.update({
  id: '/practice-tests/$certId',
  path: '/practice-tests/$certId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionQuizTopicIdRoute = SectionQuizTopicIdRouteImport.update({
  id: '/section-quiz/$topicId',
  path: '/section-quiz/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const StageExamStageIdRoute = StageExamStageIdRouteImport.update({
  id: '/stage-exam/$stageId',
  path: '/stage-exam/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksIndexRoute = TracksIndexRouteImport.update({
  id: '/tracks/',
  path: '/tracks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksSlugRoute = TracksSlugRouteImport.update({
  id: '/tracks/$slug',
  path: '/tracks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTutorStreamRoute = ApiAiTutorStreamRouteImport.update({
  id: '/api/ai/tutor-stream',
  path: '/api/ai/tutor-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMicrosoftRoute = ApiAuthMicrosoftRouteImport.update({
  id: '/api/auth/microsoft',
  path: '/api/auth/microsoft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContentAuditRoute = ApiPublicContentAuditRouteImport.update({
  id: '/api/public/content-audit',
  path: '/api/public/content-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkCheckRoute = ApiPublicLinkCheckRouteImport.update({
  id: '/api/public/link-check',
  path: '/api/public/link-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetSyncRoute = ApiPublicSheetSyncRouteImport.update({
  id: '/api/public/sheet-sync',
  path: '/api/public/sheet-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMicrosoftCallbackRoute =
  ApiAuthMicrosoftCallbackRouteImport.update({
    id: '/callback',
    path: '/callback',
    getParentRoute: () => ApiAuthMicrosoftRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/ai-tutor': typeof AiTutorRoute
  '/ai-usage': typeof AiUsageRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/byte-break': typeof ByteBreakRoute
  '/career-mode': typeof CareerModeRoute
  '/career-skills': typeof CareerSkillsRoute
  '/command-line': typeof CommandLineRoute
  '/community': typeof CommunityRoute
  '/daily-challenge': typeof DailyChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/engine-simulator': typeof EngineSimulatorRoute
  '/exam': typeof ExamRoute
  '/explore-engine': typeof ExploreEngineRoute
  '/explore-hardware': typeof ExploreHardwareRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/knowledge': typeof KnowledgeRoute
  '/labs': typeof LabsRoute
  '/learn': typeof LearnRouteWithChildren
  '/learner': typeof LearnerRoute
  '/meditation': typeof MeditationRoute
  '/meet-gayl': typeof MeetGaylRoute
  '/messages': typeof MessagesRoute
  '/my-path': typeof MyPathRoute
  '/notifications': typeof NotificationsRoute
  '/obd-scanner': typeof ObdScannerRoute
  '/pomodoro': typeof PomodoroRoute
  '/portfolio': typeof PortfolioRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/quiz-me': typeof QuizMeRoute
  '/record': typeof RecordRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-plan': typeof StudyPlanRoute
  '/tech-jobs': typeof TechJobsRoute
  '/tech-news': typeof TechNewsRoute
  '/tech-videos': typeof TechVideosRoute
  '/terms': typeof TermsRoute
  '/troubleshoot': typeof TroubleshootRoute
  '/virtual-mobile': typeof VirtualMobileRoute
  '/virtual-pc': typeof VirtualPcRoute
  '/virus': typeof VirusRoute
  '/weak-areas': typeof WeakAreasRoute
  '/certifications/$certId': typeof CertificationsCertIdRoute
  '/flashcards/$topicId': typeof FlashcardsTopicIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/learn/videos': typeof LearnVideosRoute
  '/practice-tests/$certId': typeof PracticeTestsCertIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/section-quiz/$topicId': typeof SectionQuizTopicIdRoute
  '/stage-exam/$stageId': typeof StageExamStageIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/certifications/': typeof CertificationsIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/practice-tests/': typeof PracticeTestsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/tracks/': typeof TracksIndexRoute
  '/api/ai/tutor-stream': typeof ApiAiTutorStreamRoute
  '/api/auth/microsoft': typeof ApiAuthMicrosoftRouteWithChildren
  '/api/public/content-audit': typeof ApiPublicContentAuditRoute
  '/api/public/link-check': typeof ApiPublicLinkCheckRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/api/auth/microsoft/callback': typeof ApiAuthMicrosoftCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/ai-tutor': typeof AiTutorRoute
  '/ai-usage': typeof AiUsageRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/byte-break': typeof ByteBreakRoute
  '/career-mode': typeof CareerModeRoute
  '/career-skills': typeof CareerSkillsRoute
  '/command-line': typeof CommandLineRoute
  '/community': typeof CommunityRoute
  '/daily-challenge': typeof DailyChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/engine-simulator': typeof EngineSimulatorRoute
  '/exam': typeof ExamRoute
  '/explore-engine': typeof ExploreEngineRoute
  '/explore-hardware': typeof ExploreHardwareRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/knowledge': typeof KnowledgeRoute
  '/labs': typeof LabsRoute
  '/learn': typeof LearnRouteWithChildren
  '/learner': typeof LearnerRoute
  '/meditation': typeof MeditationRoute
  '/meet-gayl': typeof MeetGaylRoute
  '/messages': typeof MessagesRoute
  '/my-path': typeof MyPathRoute
  '/notifications': typeof NotificationsRoute
  '/obd-scanner': typeof ObdScannerRoute
  '/pomodoro': typeof PomodoroRoute
  '/portfolio': typeof PortfolioRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/quiz-me': typeof QuizMeRoute
  '/record': typeof RecordRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-plan': typeof StudyPlanRoute
  '/tech-jobs': typeof TechJobsRoute
  '/tech-news': typeof TechNewsRoute
  '/tech-videos': typeof TechVideosRoute
  '/terms': typeof TermsRoute
  '/troubleshoot': typeof TroubleshootRoute
  '/virtual-mobile': typeof VirtualMobileRoute
  '/virtual-pc': typeof VirtualPcRoute
  '/virus': typeof VirusRoute
  '/weak-areas': typeof WeakAreasRoute
  '/certifications/$certId': typeof CertificationsCertIdRoute
  '/flashcards/$topicId': typeof FlashcardsTopicIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/learn/videos': typeof LearnVideosRoute
  '/practice-tests/$certId': typeof PracticeTestsCertIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/section-quiz/$topicId': typeof SectionQuizTopicIdRoute
  '/stage-exam/$stageId': typeof StageExamStageIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/certifications': typeof CertificationsIndexRoute
  '/flashcards': typeof FlashcardsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/practice-tests': typeof PracticeTestsIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/tracks': typeof TracksIndexRoute
  '/api/ai/tutor-stream': typeof ApiAiTutorStreamRoute
  '/api/auth/microsoft': typeof ApiAuthMicrosoftRouteWithChildren
  '/api/public/content-audit': typeof ApiPublicContentAuditRoute
  '/api/public/link-check': typeof ApiPublicLinkCheckRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/api/auth/microsoft/callback': typeof ApiAuthMicrosoftCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRoute
  '/ai-tutor': typeof AiTutorRoute
  '/ai-usage': typeof AiUsageRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/byte-break': typeof ByteBreakRoute
  '/career-mode': typeof CareerModeRoute
  '/career-skills': typeof CareerSkillsRoute
  '/command-line': typeof CommandLineRoute
  '/community': typeof CommunityRoute
  '/daily-challenge': typeof DailyChallengeRoute
  '/dashboard': typeof DashboardRoute
  '/engine-simulator': typeof EngineSimulatorRoute
  '/exam': typeof ExamRoute
  '/explore-engine': typeof ExploreEngineRoute
  '/explore-hardware': typeof ExploreHardwareRoute
  '/guide': typeof GuideRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/knowledge': typeof KnowledgeRoute
  '/labs': typeof LabsRoute
  '/learn': typeof LearnRouteWithChildren
  '/learner': typeof LearnerRoute
  '/meditation': typeof MeditationRoute
  '/meet-gayl': typeof MeetGaylRoute
  '/messages': typeof MessagesRoute
  '/my-path': typeof MyPathRoute
  '/notifications': typeof NotificationsRoute
  '/obd-scanner': typeof ObdScannerRoute
  '/pomodoro': typeof PomodoroRoute
  '/portfolio': typeof PortfolioRoute
  '/practice': typeof PracticeRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/quiz-me': typeof QuizMeRoute
  '/record': typeof RecordRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-plan': typeof StudyPlanRoute
  '/tech-jobs': typeof TechJobsRoute
  '/tech-news': typeof TechNewsRoute
  '/tech-videos': typeof TechVideosRoute
  '/terms': typeof TermsRoute
  '/troubleshoot': typeof TroubleshootRoute
  '/virtual-mobile': typeof VirtualMobileRoute
  '/virtual-pc': typeof VirtualPcRoute
  '/virus': typeof VirusRoute
  '/weak-areas': typeof WeakAreasRoute
  '/certifications/$certId': typeof CertificationsCertIdRoute
  '/flashcards/$topicId': typeof FlashcardsTopicIdRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/learn/videos': typeof LearnVideosRoute
  '/practice-tests/$certId': typeof PracticeTestsCertIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/section-quiz/$topicId': typeof SectionQuizTopicIdRoute
  '/stage-exam/$stageId': typeof StageExamStageIdRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/tracks/$slug': typeof TracksSlugRoute
  '/certifications/': typeof CertificationsIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/practice-tests/': typeof PracticeTestsIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/tracks/': typeof TracksIndexRoute
  '/api/ai/tutor-stream': typeof ApiAiTutorStreamRoute
  '/api/auth/microsoft': typeof ApiAuthMicrosoftRouteWithChildren
  '/api/public/content-audit': typeof ApiPublicContentAuditRoute
  '/api/public/link-check': typeof ApiPublicLinkCheckRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/api/auth/microsoft/callback': typeof ApiAuthMicrosoftCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/ai-tutor'
    | '/ai-usage'
    | '/auth'
    | '/bookmarks'
    | '/byte-break'
    | '/career-mode'
    | '/career-skills'
    | '/command-line'
    | '/community'
    | '/daily-challenge'
    | '/dashboard'
    | '/engine-simulator'
    | '/exam'
    | '/explore-engine'
    | '/explore-hardware'
    | '/guide'
    | '/insights'
    | '/journey'
    | '/knowledge'
    | '/labs'
    | '/learn'
    | '/learner'
    | '/meditation'
    | '/meet-gayl'
    | '/messages'
    | '/my-path'
    | '/notifications'
    | '/obd-scanner'
    | '/pomodoro'
    | '/portfolio'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/quiz-me'
    | '/record'
    | '/refund-policy'
    | '/reset-password'
    | '/resources'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/study-plan'
    | '/tech-jobs'
    | '/tech-news'
    | '/tech-videos'
    | '/terms'
    | '/troubleshoot'
    | '/virtual-mobile'
    | '/virtual-pc'
    | '/virus'
    | '/weak-areas'
    | '/certifications/$certId'
    | '/flashcards/$topicId'
    | '/guides/$slug'
    | '/learn/videos'
    | '/practice-tests/$certId'
    | '/profile/$userId'
    | '/section-quiz/$topicId'
    | '/stage-exam/$stageId'
    | '/topics/$topicId'
    | '/tracks/$slug'
    | '/certifications/'
    | '/flashcards/'
    | '/guides/'
    | '/practice-tests/'
    | '/topics/'
    | '/tracks/'
    | '/api/ai/tutor-stream'
    | '/api/auth/microsoft'
    | '/api/public/content-audit'
    | '/api/public/link-check'
    | '/api/public/sheet-sync'
    | '/api/auth/microsoft/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/ai-tutor'
    | '/ai-usage'
    | '/auth'
    | '/bookmarks'
    | '/byte-break'
    | '/career-mode'
    | '/career-skills'
    | '/command-line'
    | '/community'
    | '/daily-challenge'
    | '/dashboard'
    | '/engine-simulator'
    | '/exam'
    | '/explore-engine'
    | '/explore-hardware'
    | '/guide'
    | '/insights'
    | '/journey'
    | '/knowledge'
    | '/labs'
    | '/learn'
    | '/learner'
    | '/meditation'
    | '/meet-gayl'
    | '/messages'
    | '/my-path'
    | '/notifications'
    | '/obd-scanner'
    | '/pomodoro'
    | '/portfolio'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/quiz-me'
    | '/record'
    | '/refund-policy'
    | '/reset-password'
    | '/resources'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/study-plan'
    | '/tech-jobs'
    | '/tech-news'
    | '/tech-videos'
    | '/terms'
    | '/troubleshoot'
    | '/virtual-mobile'
    | '/virtual-pc'
    | '/virus'
    | '/weak-areas'
    | '/certifications/$certId'
    | '/flashcards/$topicId'
    | '/guides/$slug'
    | '/learn/videos'
    | '/practice-tests/$certId'
    | '/profile/$userId'
    | '/section-quiz/$topicId'
    | '/stage-exam/$stageId'
    | '/topics/$topicId'
    | '/tracks/$slug'
    | '/certifications'
    | '/flashcards'
    | '/guides'
    | '/practice-tests'
    | '/topics'
    | '/tracks'
    | '/api/ai/tutor-stream'
    | '/api/auth/microsoft'
    | '/api/public/content-audit'
    | '/api/public/link-check'
    | '/api/public/sheet-sync'
    | '/api/auth/microsoft/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/admin'
    | '/ai-tutor'
    | '/ai-usage'
    | '/auth'
    | '/bookmarks'
    | '/byte-break'
    | '/career-mode'
    | '/career-skills'
    | '/command-line'
    | '/community'
    | '/daily-challenge'
    | '/dashboard'
    | '/engine-simulator'
    | '/exam'
    | '/explore-engine'
    | '/explore-hardware'
    | '/guide'
    | '/insights'
    | '/journey'
    | '/knowledge'
    | '/labs'
    | '/learn'
    | '/learner'
    | '/meditation'
    | '/meet-gayl'
    | '/messages'
    | '/my-path'
    | '/notifications'
    | '/obd-scanner'
    | '/pomodoro'
    | '/portfolio'
    | '/practice'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/quiz-me'
    | '/record'
    | '/refund-policy'
    | '/reset-password'
    | '/resources'
    | '/review'
    | '/settings'
    | '/sitemap.xml'
    | '/study-plan'
    | '/tech-jobs'
    | '/tech-news'
    | '/tech-videos'
    | '/terms'
    | '/troubleshoot'
    | '/virtual-mobile'
    | '/virtual-pc'
    | '/virus'
    | '/weak-areas'
    | '/certifications/$certId'
    | '/flashcards/$topicId'
    | '/guides/$slug'
    | '/learn/videos'
    | '/practice-tests/$certId'
    | '/profile/$userId'
    | '/section-quiz/$topicId'
    | '/stage-exam/$stageId'
    | '/topics/$topicId'
    | '/tracks/$slug'
    | '/certifications/'
    | '/flashcards/'
    | '/guides/'
    | '/practice-tests/'
    | '/topics/'
    | '/tracks/'
    | '/api/ai/tutor-stream'
    | '/api/auth/microsoft'
    | '/api/public/content-audit'
    | '/api/public/link-check'
    | '/api/public/sheet-sync'
    | '/api/auth/microsoft/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRoute
  AiTutorRoute: typeof AiTutorRoute
  AiUsageRoute: typeof AiUsageRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  ByteBreakRoute: typeof ByteBreakRoute
  CareerModeRoute: typeof CareerModeRoute
  CareerSkillsRoute: typeof CareerSkillsRoute
  CommandLineRoute: typeof CommandLineRoute
  CommunityRoute: typeof CommunityRoute
  DailyChallengeRoute: typeof DailyChallengeRoute
  DashboardRoute: typeof DashboardRoute
  EngineSimulatorRoute: typeof EngineSimulatorRoute
  ExamRoute: typeof ExamRoute
  ExploreEngineRoute: typeof ExploreEngineRoute
  ExploreHardwareRoute: typeof ExploreHardwareRoute
  GuideRoute: typeof GuideRoute
  InsightsRoute: typeof InsightsRoute
  JourneyRoute: typeof JourneyRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LabsRoute: typeof LabsRoute
  LearnRoute: typeof LearnRouteWithChildren
  LearnerRoute: typeof LearnerRoute
  MeditationRoute: typeof MeditationRoute
  MeetGaylRoute: typeof MeetGaylRoute
  MessagesRoute: typeof MessagesRoute
  MyPathRoute: typeof MyPathRoute
  NotificationsRoute: typeof NotificationsRoute
  ObdScannerRoute: typeof ObdScannerRoute
  PomodoroRoute: typeof PomodoroRoute
  PortfolioRoute: typeof PortfolioRoute
  PracticeRoute: typeof PracticeRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  QuizMeRoute: typeof QuizMeRoute
  RecordRoute: typeof RecordRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyPlanRoute: typeof StudyPlanRoute
  TechJobsRoute: typeof TechJobsRoute
  TechNewsRoute: typeof TechNewsRoute
  TechVideosRoute: typeof TechVideosRoute
  TermsRoute: typeof TermsRoute
  TroubleshootRoute: typeof TroubleshootRoute
  VirtualMobileRoute: typeof VirtualMobileRoute
  VirtualPcRoute: typeof VirtualPcRoute
  VirusRoute: typeof VirusRoute
  WeakAreasRoute: typeof WeakAreasRoute
  CertificationsCertIdRoute: typeof CertificationsCertIdRoute
  FlashcardsTopicIdRoute: typeof FlashcardsTopicIdRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  PracticeTestsCertIdRoute: typeof PracticeTestsCertIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  SectionQuizTopicIdRoute: typeof SectionQuizTopicIdRoute
  StageExamStageIdRoute: typeof StageExamStageIdRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  TracksSlugRoute: typeof TracksSlugRoute
  CertificationsIndexRoute: typeof CertificationsIndexRoute
  FlashcardsIndexRoute: typeof FlashcardsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  PracticeTestsIndexRoute: typeof PracticeTestsIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  TracksIndexRoute: typeof TracksIndexRoute
  ApiAiTutorStreamRoute: typeof ApiAiTutorStreamRoute
  ApiAuthMicrosoftRoute: typeof ApiAuthMicrosoftRouteWithChildren
  ApiPublicContentAuditRoute: typeof ApiPublicContentAuditRoute
  ApiPublicLinkCheckRoute: typeof ApiPublicLinkCheckRoute
  ApiPublicSheetSyncRoute: typeof ApiPublicSheetSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tutor': {
      id: '/ai-tutor'
      path: '/ai-tutor'
      fullPath: '/ai-tutor'
      preLoaderRoute: typeof AiTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-usage': {
      id: '/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/byte-break': {
      id: '/byte-break'
      path: '/byte-break'
      fullPath: '/byte-break'
      preLoaderRoute: typeof ByteBreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-mode': {
      id: '/career-mode'
      path: '/career-mode'
      fullPath: '/career-mode'
      preLoaderRoute: typeof CareerModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-skills': {
      id: '/career-skills'
      path: '/career-skills'
      fullPath: '/career-skills'
      preLoaderRoute: typeof CareerSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-line': {
      id: '/command-line'
      path: '/command-line'
      fullPath: '/command-line'
      preLoaderRoute: typeof CommandLineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-challenge': {
      id: '/daily-challenge'
      path: '/daily-challenge'
      fullPath: '/daily-challenge'
      preLoaderRoute: typeof DailyChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine-simulator': {
      id: '/engine-simulator'
      path: '/engine-simulator'
      fullPath: '/engine-simulator'
      preLoaderRoute: typeof EngineSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-engine': {
      id: '/explore-engine'
      path: '/explore-engine'
      fullPath: '/explore-engine'
      preLoaderRoute: typeof ExploreEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-hardware': {
      id: '/explore-hardware'
      path: '/explore-hardware'
      fullPath: '/explore-hardware'
      preLoaderRoute: typeof ExploreHardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner': {
      id: '/learner'
      path: '/learner'
      fullPath: '/learner'
      preLoaderRoute: typeof LearnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditation': {
      id: '/meditation'
      path: '/meditation'
      fullPath: '/meditation'
      preLoaderRoute: typeof MeditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-gayl': {
      id: '/meet-gayl'
      path: '/meet-gayl'
      fullPath: '/meet-gayl'
      preLoaderRoute: typeof MeetGaylRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-path': {
      id: '/my-path'
      path: '/my-path'
      fullPath: '/my-path'
      preLoaderRoute: typeof MyPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obd-scanner': {
      id: '/obd-scanner'
      path: '/obd-scanner'
      fullPath: '/obd-scanner'
      preLoaderRoute: typeof ObdScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro': {
      id: '/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof PomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz-me': {
      id: '/quiz-me'
      path: '/quiz-me'
      fullPath: '/quiz-me'
      preLoaderRoute: typeof QuizMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-plan': {
      id: '/study-plan'
      path: '/study-plan'
      fullPath: '/study-plan'
      preLoaderRoute: typeof StudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-jobs': {
      id: '/tech-jobs'
      path: '/tech-jobs'
      fullPath: '/tech-jobs'
      preLoaderRoute: typeof TechJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-news': {
      id: '/tech-news'
      path: '/tech-news'
      fullPath: '/tech-news'
      preLoaderRoute: typeof TechNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tech-videos': {
      id: '/tech-videos'
      path: '/tech-videos'
      fullPath: '/tech-videos'
      preLoaderRoute: typeof TechVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troubleshoot': {
      id: '/troubleshoot'
      path: '/troubleshoot'
      fullPath: '/troubleshoot'
      preLoaderRoute: typeof TroubleshootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-mobile': {
      id: '/virtual-mobile'
      path: '/virtual-mobile'
      fullPath: '/virtual-mobile'
      preLoaderRoute: typeof VirtualMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-pc': {
      id: '/virtual-pc'
      path: '/virtual-pc'
      fullPath: '/virtual-pc'
      preLoaderRoute: typeof VirtualPcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virus': {
      id: '/virus'
      path: '/virus'
      fullPath: '/virus'
      preLoaderRoute: typeof VirusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weak-areas': {
      id: '/weak-areas'
      path: '/weak-areas'
      fullPath: '/weak-areas'
      preLoaderRoute: typeof WeakAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/': {
      id: '/certifications/'
      path: '/certifications'
      fullPath: '/certifications/'
      preLoaderRoute: typeof CertificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications/$certId': {
      id: '/certifications/$certId'
      path: '/certifications/$certId'
      fullPath: '/certifications/$certId'
      preLoaderRoute: typeof CertificationsCertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof FlashcardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/$topicId': {
      id: '/flashcards/$topicId'
      path: '/flashcards/$topicId'
      fullPath: '/flashcards/$topicId'
      preLoaderRoute: typeof FlashcardsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/videos': {
      id: '/learn/videos'
      path: '/videos'
      fullPath: '/learn/videos'
      preLoaderRoute: typeof LearnVideosRouteImport
      parentRoute: typeof LearnRoute
    }
    '/practice-tests/': {
      id: '/practice-tests/'
      path: '/practice-tests'
      fullPath: '/practice-tests/'
      preLoaderRoute: typeof PracticeTestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice-tests/$certId': {
      id: '/practice-tests/$certId'
      path: '/practice-tests/$certId'
      fullPath: '/practice-tests/$certId'
      preLoaderRoute: typeof PracticeTestsCertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section-quiz/$topicId': {
      id: '/section-quiz/$topicId'
      path: '/section-quiz/$topicId'
      fullPath: '/section-quiz/$topicId'
      preLoaderRoute: typeof SectionQuizTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-exam/$stageId': {
      id: '/stage-exam/$stageId'
      path: '/stage-exam/$stageId'
      fullPath: '/stage-exam/$stageId'
      preLoaderRoute: typeof StageExamStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/': {
      id: '/tracks/'
      path: '/tracks'
      fullPath: '/tracks/'
      preLoaderRoute: typeof TracksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks/$slug': {
      id: '/tracks/$slug'
      path: '/tracks/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof TracksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/tutor-stream': {
      id: '/api/ai/tutor-stream'
      path: '/api/ai/tutor-stream'
      fullPath: '/api/ai/tutor-stream'
      preLoaderRoute: typeof ApiAiTutorStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/microsoft': {
      id: '/api/auth/microsoft'
      path: '/api/auth/microsoft'
      fullPath: '/api/auth/microsoft'
      preLoaderRoute: typeof ApiAuthMicrosoftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/content-audit': {
      id: '/api/public/content-audit'
      path: '/api/public/content-audit'
      fullPath: '/api/public/content-audit'
      preLoaderRoute: typeof ApiPublicContentAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/link-check': {
      id: '/api/public/link-check'
      path: '/api/public/link-check'
      fullPath: '/api/public/link-check'
      preLoaderRoute: typeof ApiPublicLinkCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheet-sync': {
      id: '/api/public/sheet-sync'
      path: '/api/public/sheet-sync'
      fullPath: '/api/public/sheet-sync'
      preLoaderRoute: typeof ApiPublicSheetSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/microsoft/callback': {
      id: '/api/auth/microsoft/callback'
      path: '/callback'
      fullPath: '/api/auth/microsoft/callback'
      preLoaderRoute: typeof ApiAuthMicrosoftCallbackRouteImport
      parentRoute: typeof ApiAuthMicrosoftRoute
    }
  }
}

interface LearnRouteChildren {
  LearnVideosRoute: typeof LearnVideosRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnVideosRoute: LearnVideosRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface ApiAuthMicrosoftRouteChildren {
  ApiAuthMicrosoftCallbackRoute: typeof ApiAuthMicrosoftCallbackRoute
}

const ApiAuthMicrosoftRouteChildren: ApiAuthMicrosoftRouteChildren = {
  ApiAuthMicrosoftCallbackRoute: ApiAuthMicrosoftCallbackRoute,
}

const ApiAuthMicrosoftRouteWithChildren =
  ApiAuthMicrosoftRoute._addFileChildren(ApiAuthMicrosoftRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRoute,
  AiTutorRoute: AiTutorRoute,
  AiUsageRoute: AiUsageRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  ByteBreakRoute: ByteBreakRoute,
  CareerModeRoute: CareerModeRoute,
  CareerSkillsRoute: CareerSkillsRoute,
  CommandLineRoute: CommandLineRoute,
  CommunityRoute: CommunityRoute,
  DailyChallengeRoute: DailyChallengeRoute,
  DashboardRoute: DashboardRoute,
  EngineSimulatorRoute: EngineSimulatorRoute,
  ExamRoute: ExamRoute,
  ExploreEngineRoute: ExploreEngineRoute,
  ExploreHardwareRoute: ExploreHardwareRoute,
  GuideRoute: GuideRoute,
  InsightsRoute: InsightsRoute,
  JourneyRoute: JourneyRoute,
  KnowledgeRoute: KnowledgeRoute,
  LabsRoute: LabsRoute,
  LearnRoute: LearnRouteWithChildren,
  LearnerRoute: LearnerRoute,
  MeditationRoute: MeditationRoute,
  MeetGaylRoute: MeetGaylRoute,
  MessagesRoute: MessagesRoute,
  MyPathRoute: MyPathRoute,
  NotificationsRoute: NotificationsRoute,
  ObdScannerRoute: ObdScannerRoute,
  PomodoroRoute: PomodoroRoute,
  PortfolioRoute: PortfolioRoute,
  PracticeRoute: PracticeRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  QuizMeRoute: QuizMeRoute,
  RecordRoute: RecordRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyPlanRoute: StudyPlanRoute,
  TechJobsRoute: TechJobsRoute,
  TechNewsRoute: TechNewsRoute,
  TechVideosRoute: TechVideosRoute,
  TermsRoute: TermsRoute,
  TroubleshootRoute: TroubleshootRoute,
  VirtualMobileRoute: VirtualMobileRoute,
  VirtualPcRoute: VirtualPcRoute,
  VirusRoute: VirusRoute,
  WeakAreasRoute: WeakAreasRoute,
  CertificationsCertIdRoute: CertificationsCertIdRoute,
  FlashcardsTopicIdRoute: FlashcardsTopicIdRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  PracticeTestsCertIdRoute: PracticeTestsCertIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  SectionQuizTopicIdRoute: SectionQuizTopicIdRoute,
  StageExamStageIdRoute: StageExamStageIdRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  TracksSlugRoute: TracksSlugRoute,
  CertificationsIndexRoute: CertificationsIndexRoute,
  FlashcardsIndexRoute: FlashcardsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  PracticeTestsIndexRoute: PracticeTestsIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  TracksIndexRoute: TracksIndexRoute,
  ApiAiTutorStreamRoute: ApiAiTutorStreamRoute,
  ApiAuthMicrosoftRoute: ApiAuthMicrosoftRouteWithChildren,
  ApiPublicContentAuditRoute: ApiPublicContentAuditRoute,
  ApiPublicLinkCheckRoute: ApiPublicLinkCheckRoute,
  ApiPublicSheetSyncRoute: ApiPublicSheetSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
