/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MyPathRouteImport } from './routes/my-path'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ThisWeekRouteImport } from './routes/this-week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPathRoute = MyPathRouteImport.update({
  id: '/my-path',
  path: '/my-path',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ThisWeekRoute = ThisWeekRouteImport.update({
  id: '/this-week',
  path: '/this-week',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/my-path': typeof MyPathRoute
  '/resources': typeof ResourcesRoute
  '/this-week': typeof ThisWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/my-path': typeof MyPathRoute
  '/resources': typeof ResourcesRoute
  '/this-week': typeof ThisWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRoute
  '/my-path': typeof MyPathRoute
  '/resources': typeof ResourcesRoute
  '/this-week': typeof ThisWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/learn' | '/my-path' | '/resources' | '/this-week'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/learn' | '/my-path' | '/resources' | '/this-week'
  id: '__root__' | '/' | '/learn' | '/my-path' | '/resources' | '/this-week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRoute
  MyPathRoute: typeof MyPathRoute
  ResourcesRoute: typeof ResourcesRoute
  ThisWeekRoute: typeof ThisWeekRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-path': {
      id: '/my-path'
      path: '/my-path'
      fullPath: '/my-path'
      preLoaderRoute: typeof MyPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/this-week': {
      id: '/this-week'
      path: '/this-week'
      fullPath: '/this-week'
      preLoaderRoute: typeof ThisWeekRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRoute,
  MyPathRoute: MyPathRoute,
  ResourcesRoute: ResourcesRoute,
  ThisWeekRoute: ThisWeekRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
