/**
 * Questions written by the owner in OneDrive spreadsheets.
 *
 * Generated by scripts/import-owner-questions.ts. Do not edit by hand: edit the
 * spreadsheet and run the importer again. A topic listed here uses these
 * questions in place of the generated pool.
 */
import type { Question } from "@/lib/app-data/types";

export const ownerQuestions: Record<string, Question[]> = {
  "topic-computer-hardware-basics": [
    {
      "id": "question-owner-t01-q01",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What is the primary function of the CPU in a computer system?",
      "choices": [
        "Store data permanently for long-term use",
        "Execute instructions and perform calculations",
        "Manage network connectivity and data transfer",
        "Supply power to all other components"
      ],
      "correctAnswer": [
        "Execute instructions and perform calculations"
      ],
      "acceptableAnswers": [
        "Execute instructions and perform calculations"
      ],
      "explanation": "The CPU (Central Processing Unit) is the brain of the computer, responsible for executing instructions and performing arithmetic/logical calculations. Storage devices handle permanent data, NICs manage networking, and the PSU supplies power.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q03",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "A user wants a CPU that can handle multiple tasks simultaneously without slowdown. Which CPU feature most directly improves multitasking performance?",
      "choices": [
        "Higher base clock speed",
        "Larger Level 1 cache",
        "Multiple cores",
        "A wider CPU socket"
      ],
      "correctAnswer": [
        "Multiple cores"
      ],
      "acceptableAnswers": [
        "Multiple cores"
      ],
      "explanation": "Multiple cores allow a CPU to process several threads or tasks in parallel, directly improving multitasking performance. Higher clock speed helps single-threaded tasks, larger cache reduces memory latency, and the socket type determines compatibility—not multitasking ability.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q05",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "Which statement best describes the role of the CPU socket on a motherboard?",
      "choices": [
        "It provides slots for installing RAM modules",
        "It connects the CPU to the power supply unit directly",
        "It physically and electrically connects the CPU to the motherboard",
        "It houses the BIOS chip and firmware"
      ],
      "correctAnswer": [
        "It physically and electrically connects the CPU to the motherboard"
      ],
      "acceptableAnswers": [
        "It physically and electrically connects the CPU to the motherboard"
      ],
      "explanation": "The CPU socket is the physical interface on the motherboard that secures the processor and provides electrical connections between the CPU and the rest of the system. DIMM slots hold RAM, power connectors connect to the PSU, and the BIOS chip is a separate component.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q07",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "A technician powers off a computer and later notices all open documents were lost. Which characteristic of RAM explains this?",
      "choices": [
        "RAM is non-volatile and erases on shutdown by design",
        "RAM is volatile and loses all stored data when power is removed",
        "RAM automatically saves data to the hard drive before shutdown",
        "RAM stores data in magnetic platters that demagnetize on power loss"
      ],
      "correctAnswer": [
        "RAM is volatile and loses all stored data when power is removed"
      ],
      "acceptableAnswers": [
        "RAM is volatile and loses all stored data when power is removed"
      ],
      "explanation": "RAM is volatile memory, meaning it requires continuous power to retain data. When power is removed, all data in RAM is lost. Non-volatile storage (HDD, SSD) retains data without power. RAM does not auto-save or use magnetic platters.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q09",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "Which of the following is an example of non-volatile storage?",
      "choices": [
        "DDR4 RAM",
        "CPU cache",
        "A solid-state drive (SSD)",
        "Video RAM (VRAM) on a GPU"
      ],
      "correctAnswer": [
        "A solid-state drive (SSD)"
      ],
      "acceptableAnswers": [
        "A solid-state drive (SSD)"
      ],
      "explanation": "A solid-state drive (SSD) is non-volatile storage, meaning it retains data without power. DDR4 RAM, CPU cache, and VRAM are all volatile memory types that lose their contents when power is removed.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q11",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "Which motherboard form factor is the largest and most commonly used in full-size desktop towers?",
      "choices": [
        "Mini-ITX",
        "Micro-ATX",
        "ATX",
        "Nano-ITX"
      ],
      "correctAnswer": [
        "ATX"
      ],
      "acceptableAnswers": [
        "ATX"
      ],
      "explanation": "ATX (Advanced Technology eXtended) is the standard full-size motherboard form factor, measuring approximately 305mm x 244mm, and is the most common in full-size desktop towers. Micro-ATX is smaller, Mini-ITX is even smaller, and Nano-ITX is rarely used.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q12",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What is the function of a PCIe slot on a motherboard?",
      "choices": [
        "To hold DDR RAM memory modules",
        "To provide a high-speed expansion slot for cards such as GPUs and NVMe adapters",
        "To connect the motherboard directly to the power supply",
        "To house the CMOS battery that stores BIOS settings"
      ],
      "correctAnswer": [
        "To provide a high-speed expansion slot for cards such as GPUs and NVMe adapters"
      ],
      "acceptableAnswers": [
        "To provide a high-speed expansion slot for cards such as GPUs and NVMe adapters"
      ],
      "explanation": "PCIe (Peripheral Component Interconnect Express) slots provide high-speed expansion interfaces for components like graphics cards, NVMe SSDs (via adapter), and network cards. DIMM slots hold RAM, power connectors attach to the PSU, and the CMOS battery is a coin-cell on the board.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q13",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What is the role of the chipset on a motherboard?",
      "choices": [
        "To generate the clock signal used by the CPU",
        "To manage communication between the CPU, RAM, storage, and I/O devices",
        "To regulate the voltage delivered to DIMM slots",
        "To store the bootable operating system image"
      ],
      "correctAnswer": [
        "To manage communication between the CPU, RAM, storage, and I/O devices"
      ],
      "acceptableAnswers": [
        "To manage communication between the CPU, RAM, storage, and I/O devices"
      ],
      "explanation": "The chipset acts as the traffic controller on a motherboard, managing data flow between the CPU, RAM, storage devices, and I/O peripherals. It does not generate CPU clock signals, regulate slot voltages independently, or store OS images.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q15",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What happens if the CMOS battery on a motherboard dies?",
      "choices": [
        "The system will not be able to read from any storage device",
        "The system will lose its BIOS/UEFI settings and the clock will reset on every reboot",
        "The CPU will overheat due to loss of fan control",
        "RAM modules will become unreadable until the battery is replaced"
      ],
      "correctAnswer": [
        "The system will lose its BIOS/UEFI settings and the clock will reset on every reboot"
      ],
      "acceptableAnswers": [
        "The system will lose its BIOS/UEFI settings and the clock will reset on every reboot"
      ],
      "explanation": "The CMOS battery powers the real-time clock and retains BIOS/UEFI configuration settings (date, time, boot order, hardware settings) when the computer is powered off. If it fails, the system loses these settings on each reboot. It does not affect storage access, fan control, or RAM operation.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q16",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What is the main advantage of an SSD over a traditional HDD?",
      "choices": [
        "SSDs use spinning magnetic platters for higher storage density",
        "SSDs have no moving parts, resulting in faster access times and greater durability",
        "SSDs are significantly cheaper per gigabyte than HDDs",
        "SSDs require a SATA connection and cannot use PCIe"
      ],
      "correctAnswer": [
        "SSDs have no moving parts, resulting in faster access times and greater durability"
      ],
      "acceptableAnswers": [
        "SSDs have no moving parts, resulting in faster access times and greater durability"
      ],
      "explanation": "SSDs use flash memory chips with no moving parts, which results in dramatically faster read/write speeds, lower latency, and better shock resistance compared to HDDs. HDDs use spinning platters. SSDs are generally more expensive per GB, and many SSDs use PCIe (NVMe).",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q17",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What does the RPM specification on a hard disk drive (HDD) indicate?",
      "choices": [
        "The rate at which data is compressed before writing",
        "The number of read/write heads inside the drive",
        "How fast the magnetic platters spin, affecting read/write performance",
        "The maximum read speed in megabytes per second"
      ],
      "correctAnswer": [
        "How fast the magnetic platters spin, affecting read/write performance"
      ],
      "acceptableAnswers": [
        "How fast the magnetic platters spin, affecting read/write performance"
      ],
      "explanation": "RPM (Revolutions Per Minute) describes how fast the platters inside an HDD spin. Higher RPM (e.g., 7200 vs. 5400) generally means faster data access and transfer. It is not related to compression, head count, or direct MB/s specifications.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q18",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What is an NVMe SSD and how does it differ from a SATA SSD?",
      "choices": [
        "NVMe uses a SATA interface and is slower than standard SSDs",
        "NVMe connects via the PCIe bus and offers significantly higher speeds than SATA-based SSDs",
        "NVMe drives require an external power brick to operate",
        "NVMe is an older standard that preceded SATA"
      ],
      "correctAnswer": [
        "NVMe connects via the PCIe bus and offers significantly higher speeds than SATA-based SSDs"
      ],
      "acceptableAnswers": [
        "NVMe connects via the PCIe bus and offers significantly higher speeds than SATA-based SSDs"
      ],
      "explanation": "NVMe (Non-Volatile Memory Express) is a protocol designed for SSDs that communicates over the PCIe bus, delivering read/write speeds several times faster than SATA SSDs. SATA SSDs are limited by the SATA interface (~600 MB/s). NVMe drives are self-powered via the slot and are a newer standard than SATA.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q19",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "Which physical form factor do most NVMe SSDs use when installed directly on a motherboard?",
      "choices": [
        "3.5-inch bay",
        "2.5-inch SATA",
        "M.2",
        "PCIe add-in card only"
      ],
      "correctAnswer": [
        "M.2"
      ],
      "acceptableAnswers": [
        "M.2"
      ],
      "explanation": "Most NVMe SSDs use the M.2 form factor, which is a small card that plugs directly into an M.2 slot on the motherboard. 3.5-inch and 2.5-inch form factors are used by HDDs and SATA SSDs respectively. NVMe can also use PCIe add-in cards but M.2 is the most common consumer form.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q20",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "A user notices that their HDD is significantly slower than their friend's drive. The user's HDD spins at 5400 RPM while the friend's spins at 7200 RPM. Why is the friend's drive faster?",
      "choices": [
        "The friend's drive has a larger cache buffer and more read/write heads",
        "Faster platter rotation means the read/write head reaches data sooner, reducing latency and increasing throughput",
        "The friend's drive uses PCIe instead of SATA",
        "The friend's drive is an SSD disguised as an HDD"
      ],
      "correctAnswer": [
        "Faster platter rotation means the read/write head reaches data sooner, reducing latency and increasing throughput"
      ],
      "acceptableAnswers": [
        "Faster platter rotation means the read/write head reaches data sooner, reducing latency and increasing throughput"
      ],
      "explanation": "A higher RPM means the magnetic platters rotate faster, so the read/write head encounters the desired data sectors more quickly. This reduces rotational latency and improves overall throughput. Cache and head count are separate factors, and standard HDDs use SATA—not PCIe.",
      "difficulty": "standard",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q22",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What does the 80 Plus certification on a power supply unit indicate?",
      "choices": [
        "The PSU can deliver at least 80 watts to the system at peak load",
        "The PSU is at least 80% efficient at converting AC power to DC power under specified loads",
        "The PSU has passed 80 hours of continuous load testing",
        "The PSU provides 80A of current on the 12V rail"
      ],
      "correctAnswer": [
        "The PSU is at least 80% efficient at converting AC power to DC power under specified loads"
      ],
      "acceptableAnswers": [
        "The PSU is at least 80% efficient at converting AC power to DC power under specified loads"
      ],
      "explanation": "80 Plus certification guarantees that the PSU is at least 80% efficient at 20%, 50%, and 100% loads, meaning at most 20% of power is wasted as heat. Higher tiers (Bronze, Silver, Gold, Platinum, Titanium) indicate higher efficiency. It is not about wattage capacity, test hours, or amperage.",
      "difficulty": "challenging",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q23",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "A high-end graphics card requires a 6+2 pin PCIe power connector. Which component provides this connector?",
      "choices": [
        "The motherboard via the PCIe slot",
        "The CPU power regulator module",
        "The power supply unit (PSU)",
        "The GPU itself through a feedback loop"
      ],
      "correctAnswer": [
        "The power supply unit (PSU)"
      ],
      "acceptableAnswers": [
        "The power supply unit (PSU)"
      ],
      "explanation": "PCIe power connectors (6-pin, 8-pin/6+2-pin) are supplied by the PSU to deliver additional power to high-wattage GPUs that require more power than the PCIe slot alone provides (maximum 75W). The motherboard PCIe slot, CPU VRM, and the GPU itself do not supply this power.",
      "difficulty": "challenging",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q24",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "Which voltage rail from a PSU is primarily used by the CPU and high-performance components such as drives and fans?",
      "choices": [
        "3.3V rail",
        "5V rail",
        "12V rail",
        "-12V rail"
      ],
      "correctAnswer": [
        "12V rail"
      ],
      "acceptableAnswers": [
        "12V rail"
      ],
      "explanation": "The 12V rail is the primary rail used by CPUs, motors in HDDs and optical drives, fans, and GPUs—the most power-hungry components. The 3.3V and 5V rails power logic circuits, USB ports, and storage controllers. The -12V rail is used for legacy serial ports and is rarely significant today.",
      "difficulty": "challenging",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q25",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "A technician is building a workstation with a 250W CPU, a 300W GPU, 50W for RAM and storage, and 50W overhead. What is the minimum PSU wattage recommended?",
      "choices": [
        "500W",
        "600W",
        "650W",
        "700W"
      ],
      "correctAnswer": [
        "650W"
      ],
      "acceptableAnswers": [
        "650W"
      ],
      "explanation": "Total load = 250 + 300 + 50 + 50 = 650W. Best practice is to choose a PSU rated at or slightly above the calculated total load to ensure efficiency and headroom. 500W and 600W are insufficient; 700W works but 650W is the minimum recommended match for this scenario.",
      "difficulty": "challenging",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q26",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What is the POST process and when does it occur?",
      "choices": [
        "It is a software utility that optimizes OS startup files after login",
        "It is a self-diagnostic test run by the BIOS/UEFI firmware immediately when the computer is powered on, before the OS loads",
        "It is a memory check performed by the operating system during shutdown",
        "It is a network connectivity test run by the NIC during boot"
      ],
      "correctAnswer": [
        "It is a self-diagnostic test run by the BIOS/UEFI firmware immediately when the computer is powered on, before the OS loads"
      ],
      "acceptableAnswers": [
        "It is a self-diagnostic test run by the BIOS/UEFI firmware immediately when the computer is powered on, before the OS loads"
      ],
      "explanation": "POST (Power-On Self-Test) is a diagnostic routine executed by the BIOS/UEFI firmware the moment a computer is powered on. It checks hardware components (CPU, RAM, GPU, storage) for functionality before handing control to the bootloader. It is not an OS utility, shutdown check, or network test.",
      "difficulty": "challenging",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q27",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "What is the function of the system bus in a computer?",
      "choices": [
        "To regulate power delivery from the PSU to individual components",
        "To carry data, addresses, and control signals between the CPU, memory, and other hardware",
        "To provide a physical pathway for cooling air across the motherboard",
        "To manage wireless communication between peripherals and the CPU"
      ],
      "correctAnswer": [
        "To carry data, addresses, and control signals between the CPU, memory, and other hardware"
      ],
      "acceptableAnswers": [
        "To carry data, addresses, and control signals between the CPU, memory, and other hardware"
      ],
      "explanation": "The system bus is a communication pathway consisting of the data bus, address bus, and control bus, which together carry information between the CPU, RAM, and other components. It is not involved in power regulation, airflow, or wireless communication.",
      "difficulty": "challenging",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q28",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "A technician is about to install a new RAM stick. Which safety precaution is most important to prevent damage from electrostatic discharge (ESD)?",
      "choices": [
        "Wear insulated rubber gloves to block all electrical contact",
        "Work in a warm, humid environment to prevent static buildup",
        "Use an anti-static wrist strap connected to a grounded metal surface before handling components",
        "Hold the RAM stick only by its gold contacts to discharge static"
      ],
      "correctAnswer": [
        "Use an anti-static wrist strap connected to a grounded metal surface before handling components"
      ],
      "acceptableAnswers": [
        "Use an anti-static wrist strap connected to a grounded metal surface before handling components"
      ],
      "explanation": "An anti-static wrist strap continuously grounds the technician, safely dissipating any static charge before it can damage sensitive components. Rubber gloves block grounding. High humidity helps but is not a reliable controlled measure. Touching gold contacts introduces oils and can cause further damage.",
      "difficulty": "challenging",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    },
    {
      "id": "question-owner-t01-q30",
      "topicId": "topic-computer-hardware-basics",
      "quizId": "section-quiz-topic-computer-hardware-basics",
      "certificationId": "cert-comptia-tech-plus",
      "type": "multiple_choice",
      "prompt": "A user wants to install a new dedicated GPU into a desktop that currently uses integrated graphics. Which of the following correctly describes the installation process and component interactions?",
      "choices": [
        "Insert the GPU into a SATA port, connect a USB cable for data, and update drivers",
        "Insert the GPU into a PCIe x16 slot, connect the required PSU power cables, secure with a screw, then install drivers and configure display output",
        "Connect the GPU to the CPU directly using a ribbon cable, then plug the monitor into the motherboard",
        "Plug the GPU into a DIMM slot and install the manufacturer's software to activate it"
      ],
      "correctAnswer": [
        "Insert the GPU into a PCIe x16 slot, connect the required PSU power cables, secure with a screw, then install drivers and configure display output"
      ],
      "acceptableAnswers": [
        "Insert the GPU into a PCIe x16 slot, connect the required PSU power cables, secure with a screw, then install drivers and configure display output"
      ],
      "explanation": "A dedicated GPU installs into the PCIe x16 slot for high-bandwidth data communication, requires power connectors from the PSU if the card exceeds 75W, is secured with a bracket screw, and needs driver installation. GPUs do not use SATA or USB data connections, ribbon cables to the CPU, or DIMM slots.",
      "difficulty": "challenging",
      "mistakeCategory": "concept",
      "requiresReasoning": false
    }
  ]
};
